### ISSUE TITLE
tidal-dl convert mp4 to m4a function

### ISSUE THREAD

**Issue by NoDowt** [exislow/tidal-dl-ng#1]
Hi, just came across your project of tidal-dl-ng and think this could be promising to see active development on this again.

A while back, i posted a bug on the GUI version of Tidal-DL, not sure if this is something you'd be able to look at with your efforts here.
https://github.com/yaronzz/Tidal-Media-Downloader-PRO/issues/276

I'm not savy enough with git to be able to suggest a fix in the code, however it seems like the original tidal-dl would actually run a re-encode of the audio (lowering quality + tacking longer); rather than simply extracting it from the Mp4.

using ffmpeg, its quite simple to do this without loss of quality with the following command:
ffmpeg -i input-video.mp4 -vn -acodec copy output-audio.m4a

Cheers!

**Comment by exislow** [comment]
I do not have a feature implemented (and also haven't planned to do so) to convert videos or extract audio. This is truely possible but can you please explain, why you would like to extract the audio from a video if you simply could download the audio file?

I am asking, because I do not plan to re-implement a ffmpeg frontend or similar. I am thinking about to implement a feature, which will convert the TS video to mp4.

**Comment by NoDowt** [comment]
Ah so it seems this might not be required at all actually having done a little test now...

Seems this might have come from having only used Tidal-Gui.exe before, rather than Tidal-DL.exe...
The convert mp4 to m4a function seems to only be part of the GUI version. When downloading a song (audio only) via the GUI version, the file it creates is an mp4. So i tried using the convert option to swap it to m4a, which I noticed dropped the quality of the output file & thus created that above issue on the original project.

Downloading the same via Tidal-dl.exe, it does indeed just output as a m4a natively... Interestingly, the file size is different to the mp4 downloaded via Tidal-GUI (both set to 'high' audio).

So the whole mp4 file output for audio is probably just a bug in the GUI verisons file name coding...
and the convert mp4 to m4a was probably intended for extracting audio from video (in which case though, my original point of using '-vn -acodec copy' rather than actually re-encoding, would still stand).

I guess there is some use to the extracting audio from video, as there are a few songs i've come across which are only available in video format. (Random one that comes to mind is the "Scream & Shout" remix with Diddy, Lil Wayne etc...)... But would be limited (and easily done externally anyway for the limited cases its needed).

**Comment by exislow** [comment]
Thank you for explaining the situation in a comprehensive way. To be honest: I have not used the `Tidal-dl.exe` or `Tidal-GUI.exe` that much before. The code is a mess and I have not got much of the idea behind the functionalities. This is an implementation of a TIDAL downloader in a clean way. I will also soon place it on PyPi. If you have any ideas about new features I am really glad to hear them.

**Comment by NoDowt** [comment]
I’ve not really delved into python much, so just used the compiled versions for simplicity…

in my day job I work with simple powershell & batch scripts quite a bit; maybe it’s time I started to take a poke around python.

Keen to see this tool develop further 👍🏼

**Comment by exislow** [comment]
There will definitely be a compiled version soon :-)

**Comment by exislow** [comment]
Try the GUI version of this tool, see https://github.com/exislow/tidal-dl-ng#-installation--upgrade

**Comment by NoDowt** [comment]
Will try to check it out in the next couple of days... Have to workout getting started with python first hah
