### ISSUE TITLE
[Feature] logout command/ force login when already logged in

### ISSUE THREAD

**Issue by pingwinekZ** [exislow/tidal-dl-ng#101]
### Current Situation

There's no option to logout and switch accounts with commands after logging in once.

### Suggestion / Feature Request

Add a "logout" command or add "force" argument to start the login process again to "login" command when logged in

**Comment by exislow** [comment]
Do you mean for the CLI interface?

**Comment by pingwinekZ** [comment]
yes, I dont use gui so I forgot to specify that I mean CLI. I see you already did it, thank u
