### ISSUE TITLE
[Feature] Run FFMPEG without a terminal windows opening up

### ISSUE THREAD

**Issue by Plastermaster** [exislow/tidal-dl-ng#103]
### Current Situation

Currently, with FFMPEG added in the settings for the conversion, it's opening a new window for a split second after each download. This results in the window focus to be disturbed as now the terminal (I assume CMD here) is taking over the window focus, but it's not always returning the focus to the previously focused window, interrupting use of the computer, especially during larger downloads of full playlists.

### Suggestion / Feature Request

If possible, it would be convenient if the use of FFMPEG didn't cause a visible window to show up at all and simply run in the background.

**Comment by Plastermaster** [comment]
Looking around I've found this possible solution, but I don't know how much this might disrupt the current structure of the program. https://github.com/kkroening/ffmpeg-python/issues/686#issuecomment-1189572497
https://stackoverflow.com/questions/62968888/how-to-hide-console-output-of-ffmpeg-in-python/71741286#71741286

**Comment by exislow** [comment]
What OS are you seeing this baviour on?

**Comment by Plastermaster** [comment]
> What OS are you seeing this baviour on?

I'm on windows 11, 23H2

**Comment by exislow** [comment]
I have applied this suggestion: https://stackoverflow.com/a/76146125

Please check, if this helps. If not, please also re-open this issue.

**Comment by Jazinity** [comment]
> I have applied this suggestion: https://stackoverflow.com/a/76146125
> 
> Please check, if this helps. If not, please also re-open this issue.

Does not seem to have fixed it. Still pops up for me.

**Comment by grimsandwich** [comment]
I think this method might work better, running it in subprocess without windows:
https://stackoverflow.com/a/65719601

**Comment by exislow** [comment]
The used library `ffmpeg-python` needs to be changed as suggested here: https://stackoverflow.com/a/74931189

Maybe you can raise an issue regarding that over there at the `ffmpeg-python` repo or you could try to follow up this one https://github.com/kkroening/ffmpeg-python/issues/805
