### ISSUE TITLE
[Bug] Cannot load artwork for flac

### ISSUE THREAD

**Issue by apostoiis** [exislow/tidal-dl-ng#104]
### What happened?

Set `extract_flac` to true
Installed FFmpeg
Set path `/opt/homebrew/bin/ffmpeg`

Although FLAC is extracted artwork is not loaded.
If `.m4a` is downloaded then the artwork is loaded.

screenshot from Rekordbox
<img width="583" alt="Screenshot 2024-05-12 at 12 37 03" src="https://github.com/exislow/tidal-dl-ng/assets/1668563/1b813540-9d72-4c8c-ace6-c31803c10115">

### Version App

0.13.2

### What operating system are you seeing the problem on?

macOS

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": false, "download_delay": true, "download_base_path": "/Users/apostolis.taxidaridis/Music/Tidal/Playlists", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "360", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "/opt/homebrew/bin/ffmpeg", "metadata_cover_dimension": "320", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by exislow** [comment]
Please paste the output of `mediainfo /path/to/song.flac`.
