### ISSUE TITLE
[Help]  "extract_flac"

### ISSUE THREAD

**Issue by vad62** [exislow/tidal-dl-ng#107]
### I need Help.

I need Help for FFmpeg.

### What operating system are you seeing the problem on?

macOS

Installed options "extract_flac". The path to the file FFmpeg.exe is specified in the settings. When the program starts it shows "All setup". After downloading the first track, the queue stops and the download cannot be deleted. Without the " extract_flac" option everything works. The FFmpeg.exe file is in the specified directory in the settings. What am I doing wrong, please help.

**Comment by amoreyeah** [comment]
Same problem. MacOS 12.7.3, tried static FFmpeg binaries ffmpeg-115255 and ffmpeg-6.1.1 all the same.

**Comment by exislow** [comment]
I cannot help you if you do not provide any evidence (screenshots and logs) and no information for re-production. Also config is missing. Try the latest version of this app. If the error still exists, please open a "BUG" issue and provide a vast amount if information.
