### ISSUE TITLE
[Feature] Adding option for downloading playlists as .m3u

### ISSUE THREAD

**Issue by amoreyeah** [exislow/tidal-dl-ng#108]
### Current Situation

There is no such option.

### Suggestion / Feature Request

It would be nice to download all the tracks from the playlists sorted by artist and album (or any other structure of user choice) and add a .m3u file to the /Playlists folder

**Comment by exislow** [comment]
Feel free to get me a pull request for this. But let the user decide, how the order should be (make it flexible).

**Comment by juxuanu** [comment]
Generating m3u files from existing playlists would be awesome. This way you could download all tracks, generate the m3u file from a given playlist and import it somewhere else to completely move playlists without having to redownload songs for each playlist in a new folder.

**Comment by exislow** [comment]
It is now implemented. Check this option `playlist_create`.

Also very handy in combination with `symlink_to_track`, which can create basically virtual playlists with one central directory for all tracks. Do more duplicates.
