### ISSUE TITLE
Ability to ignore file extensions

### ISSUE THREAD

**Issue by rudy-lath-vizio** [exislow/tidal-dl-ng#11]
Currently, when we download a playlist, the program will check if the file already exists in the playlist folder. It would be nice to have a config field that just checks the name of the file and not the extension.

USE CASE: As a DJ, you might want to convert all your downloaded files to a different format within the same folder to avoid unnecessary copies, having this feature will allow us to maintain a unified directory for downloading and consumption, ultimately being able to download only new songs in that playlist regardless of file extension.

**Comment by exislow** [comment]
I got your idea and will look into it, as soon as I have a little bit more time. Feel free to get me a pull request, if you like.
