### ISSUE TITLE
[Help] Windows Error 2

### ISSUE THREAD

**Issue by bjg83** [exislow/tidal-dl-ng#110]
### I need Help.

Just installed new version (v.0.14.0) and logged in to Tidal fine. I set up the download directories and the ffmpeg path. But whenever I try to download anything, after the file reaches 100% I get this error in the console: 

"[WinError 2] The system cannot find the file specified"

No files (or subfolders) are in the download directory.

I'm not sure which file is unspecified here in this error.

Any help would be great. Thanks!

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "Downloads\\Music\\Tidal", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists\\{playlist_name}\\{artist_name} - {track_title}", "format_mix": "Mix\\{mix_name}\\{artist_name} - {track_title}", "format_track": "Tracks\\{artist_name} - {track_title}{track_explicit}", "format_video": "Videos\\{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": true, "path_binary_ffmpeg": "\\Downloads\\Compressed\\TIDAL-Downloader-NG_windows-x64\\TIDAL-Downloader-NG\\ffmpeg.dll", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": true}
```

**Comment by bjg83** [comment]
Thanks. Made both those changes (pointing to exe and paths) and still getting the same error: "the system cannot find the file specified."

**Comment by bjg83** [comment]
OK. It seems to be an ffmpeg error. I unselected "extract_flac" and the download worked fine. The M4A is in the correct folder. So the conversion is the issue.

I have the latest ffmpeg and put it in the folder with Tidal-DL-NG.

**Comment by MusicLover24** [comment]
Make sure to Add to PATH the ffmpeg executable:

Right-click on This PC or Computer on the desktop or in File Explorer.
Select Properties.
Click Advanced system settings.
Click the Environment Variables button.
In the System variables section, find the Path variable and click Edit.
Click New and add the directory path to ffmpeg.exe.
Click OK to close all windows.

And then add the path to ffmpeg in this format (with the "r" in front and quotes): r"C:\path\to\ffmpeg.exe"
It worked for me like this.

**Comment by bjg83** [comment]
Thanks @MusicLover24. I would not have figured that out myself!

This might be something @exislow should note for Windows users when installing / setting up.

All working now. Files downloaded and converted to FLAC.

**Comment by thr-4** [comment]
I can confirm that the workaround works. The problem that on Windows, ffmpeg path is ignored (even if added through the path picker in GUI) remains.

**Comment by froggyking3** [comment]
> I can confirm that the workaround works. The problem that on Windows, ffmpeg path is ignored (even if added through the path picker in GUI) remains.

confirmed that toggling off convert to flac works. i have ffmpeg on my desktop in a separate folder, linking was working just fine yesterday. seems to only be for certain, random tracks. frustrating.
