### ISSUE TITLE
[Bug] Windows: 'Tidal' object has no attribute 'is_pkce'

### ISSUE THREAD

**Issue by MozgC** [exislow/tidal-dl-ng#113]
### What happened?

When I try to download anything I get:
>'Tidal' object has no attribute 'is_pkce'

### Version App

0.14.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
> Login not successful. Have fun!
> FFmpeg is not set. Videos can be downloaded but will not be processed. FLAC cannot be extracted from MP4 containers. Make sure FFmpeg is installed and the path to the binary is configured (`path_binary_ffmpeg`).
> All setup.
> Please select a mix or playlist first.
> Please select a mix or playlist first.
> 'Tidal' object has no attribute 'is_pkce'
> 'Tidal' object has no attribute 'is_pkce'
> 'Tidal' object has no attribute 'is_pkce'
> 'Tidal' object has no attribute 'is_pkce'
> 'Tidal' object has no attribute 'is_pkce'
```

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "E:\\Music\\Tidal-NG", "quality_audio": "LOSSLESS", "quality_video": "480", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "", "metadata_cover_dimension": "320", "extract_flac": false, "downgrade_on_hi_res": false}
```

**Comment by pingwinekZ** [comment]
same error on 0.15.2

**Comment by exislow** [comment]
Is fixed. Please test with v0.15.3. You need to delete `token.json` first before you start the app.

**Comment by MozgC** [comment]
@exislow that was quick! it's working now! thank you!

**Comment by MozgC** [comment]
@exislow I'm a supporter of this Windows GUI: Tidal-Media-Downloader-PRO
The original author, it seems, stopped supporting the project.
I don't know too much about internals of downloading though. Maybe you would have any idea why Tidal-Media-Downloader-PRO stopped downloading new tracks in hi-res lossless and instead downloads MQA, as users say here:
https://github.com/yaronzz//issues/290
When I tried to download the same track with  Tidal-Media-Downloader-PRO and your project,  Tidal-Media-Downloader-PRO download it in MQA flac, 1317 kbps, and your project downloaded it in hi-res m4a, 4209 kbps.
