### ISSUE TITLE
[Help] Constantly losing my config "Something is wrong with your config. Maybe it is not compatible anymore due to a new app version."

### ISSUE THREAD

**Issue by DW4y** [exislow/tidal-dl-ng#116]
### I need Help.

Hello,

I set up tidal-dl-ng on armbian and constantly becoming the error that my config is not compatible anymore as I call up tidal-dl-ng cfg.

`Something is wrong with your config. Maybe it is not compatible anymore due to a new app version. You can find a backup of your old config here: '/home/pierre/.config/tidal_dl_ng/settings.json.bak'. A new default config was created.`

Python Version: Python 3.11.2
Linux: Armbian 24.2.1 Bookworm with Linux 6.6.16-current-sunxi

Thanks,
Pierre

### What operating system are you seeing the problem on?

Linux

### Your settings

```json
{"skip_existing": "true", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "~/audio/unsorted", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": true, "path_binary_ffmpeg": "/usr/bin/ffmpeg", "metadata_cover_dimension": "320", "extract_flac": true, "downgrade_on_hi_res": true}
```

**Comment by exislow** [comment]
After this error message the app creates a valid config. If you restart the app without changing the default config, is this message showed again?
