### ISSUE TITLE
[Feature] Add option to download the cover as a separate file instead of embedding

### ISSUE THREAD

**Issue by Slinky6267** [exislow/tidal-dl-ng#125]
### Current Situation

Currently it seem you only can change the size of the embedded cover art and It can't be disabled.

### Suggestion / Feature Request

I suggest that user given the option to disable cover art downloading or download the cover separately without embedding it into the music files. Could be added to the flags section similarly to the lyrics flags.

**Comment by exislow** [comment]
Thank you for this suggestions. Disabling the embedded cover art is a valid point. Maybe you can get me a pull request on this?

How would you like to propose the download of the cover art in a separate file? If you download an album this is straightforward: We can just name it `cover.jpg` within the album folder. But what if you download single tracks, which will all be within the same folder? The cover art will be overwritten every time, if it is just called `cover.jpg`.

**Comment by GammaScorpii** [comment]
I'd like this too. Single tracks don't concern me, but here's a few suggestions.

Maybe for single tracks it could use the variable of the album name (the same one used for the directory name when saving an album) as its file name? If the album art already exists it could skip downloading to avoid overwriting the file every time a single track is downloaded from that album.

Alternatively if it's a single track and we have a way of identifying it's a single track download (since a single track download is saved without creating a folder), it could just ignore the option of saving to a separate jpg and embed anyway. But I like the first option better.

**Comment by exislow** [comment]
> Maybe for single tracks it could use the variable of the album name (the same one used for the directory name when saving an album) as its file name? If the album art already exists it could skip downloading to avoid overwriting the file every time a single track is downloaded from that album.

I like this idea but I have the following concern: If you track is named <artist> - <name>.<ext> and the cover file is named <album name>.jpg or something and you have like single 300 tracks in this folder, how are you going to find the right cover file for each track immediately? You will need to lookup the album name in the metadata for each track. Won't this be a lot of a hassle, will it?

Maybe enabling cover download only for full album would be best?

**Comment by GammaScorpii** [comment]
True, it would become messy that way, without organizing files myself. But admittedly if I were downloading single tracks, I'd prefer to have the albumart embedded anyway. This is more of a nice feature for those who download albums. So yes, to your 2nd point.

**Comment by shakasan** [comment]
Would be nice to have both as setting for embed and cover.jpg file, to allow user to match their needs (one of them or both together).
I personally only download albums and use both embed/cover.jpg together to increase "compatibility" with various hardware/software I use.

**Comment by orbittwz** [comment]
would be nice to have the downloaded item "cover.jpg" saved in the output folder.

**Comment by exislow** [comment]
I propose to have it this way: 

1. Have an option to embed album art into the file.
2. Have a separate option to download the album art to `cover.jpg`, only IF an album is downloaded. Is a single track or something else than an album is downloaded, this option will be ignored. In this case album art can be embedded, if option 1. is enabled.

What do you think?

**Comment by orbittwz** [comment]
Hi!
Album art is already embedded, so it's fine.
Just need to save the cover.jpg in the folder.
Shouldn't be optional, it's a must.

**Comment by exislow** [comment]
Fixed with https://github.com/exislow/tidal-dl-ng/commit/24d75a7c208113c56707ca48624271748454ced7
