### ISSUE TITLE
[Help] Playlists in directories are not listed

### ISSUE THREAD

**Issue by Vorbisset** [exislow/tidal-dl-ng#127]
### I need Help.

From GUI, my playlists from Tidal directories are not listed. There is a way to show them ?

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "~/download", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "480", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "", "metadata_cover_dimension": "320", "extract_flac": false, "downgrade_on_hi_res": false}
```

**Comment by exislow** [comment]
All playlists within folders are shown in the left pain but the folder names are not shown, since `tidalapi` (library this project uses) does not support them.

**Comment by AntonSoeffing** [comment]
@exislow I have lots of playlists organized in folders, its really hard for me to navigate my playlists in tidal-dl-ng without my folder hierachry.
It seems python-tidal has added support for playlist forlders [python-tidal/pull/288](https://github.com/EbbLabs/python-tidal/pull/288)

Would it be possible to add that feature? This would improve the GUI by a lot
