### ISSUE TITLE
[Help] "PermissionError: [Errno 13]" [read till bottom]

### ISSUE THREAD

**Issue by venttarc** [exislow/tidal-dl-ng#128]
![Screenshot_2024-06-12-21-51-40-05](https://github.com/exislow/tidal-dl-ng/assets/163729109/3aa9bc0d-db5f-4c6b-a7ac-c672f84784dc)
### I need Help.

I am using Linux env in my android phone using termux. The tool was just working just fine until the 0.15.4 update. It seems like something is wrong right here. Gives the error "PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/ffmpeg". I am pretty sure and have checked multiple times that I have already given all the required permissions for the tool to work and the ffmpeg binary is present at the given directory as well but idk what's wrong. A HELP WOULD BE MUCH APPRECIATED

### What operating system are you seeing the problem on?

Linux

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "/storage/emulated/0/Music", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "480", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": true, "path_binary_ffmpeg": "/storage/emulated/0/Download/ffmpeg", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": false}
```
![FULL ERROR PREVIEW](https://github.com/exislow/tidal-dl-ng/assets/163729109/da05f718-324b-4bba-9742-543e7903dd79)

**Comment by venttarc** [comment]
Proof that 0.15.3 works fine
![Screenshot_2024-06-12-22-16-06-95_84d3000e3f4017145260f7618db1d683](https://github.com/exislow/tidal-dl-ng/assets/163729109/9d06dc79-4bbb-4013-b1f3-6b5b102e9d35)

**Comment by exislow** [comment]
I do not use Android, thus I cannot help you with that. But it might be a permission issue...

**Comment by venttarc** [comment]
> I do not use Android, thus I cannot help you with that. But it might be a permission issue...

ould you kindly look into the code? the issue was not present in the previous versions. Only the new update has the issue.

**Comment by exislow** [comment]
This post show, that everything works fine: https://github.com/exislow/tidal-dl-ng/issues/128#issuecomment-2163444646

The code base is working on other operating systems. Also on desktop Linux systems, such as Ubuntu. I suggest double check all permission etc. and especially post everything necessary here. But please no screenshots of prompts. Just copy and paste the text.

**Comment by venttarc** [comment]
The post is showing that everything is working fine is because the version is not "0.15.4" but "0.15.3". Anyways, maybe its my skill issue that u can't get it to work. Thanks for your precious time. :-)
