### ISSUE TITLE
[Bug] Playlists do not update

### ISSUE THREAD

**Issue by stork-afk** [exislow/tidal-dl-ng#129]
### What happened?

I made a new playlist in Tidal.  I opened Tidal-dl and the list did not show up.  I clicked on the reload button, still the new list does not show up. Tried shutting everything down and opening again, but still the new list does not show up.

### Version App

v0.15.4

### What operating system are you seeing the problem on?

macOS

### Your settings

```json
TIDAL-Downloader-NG.plist
```

**Comment by stork-afk** [comment]
Can you give me detailed instructions of how to copy my settings, please?

**Comment by exislow** [comment]
Regarding the settings, simply read the explanatory text here: https://github.com/exislow/tidal-dl-ng/issues/new?assignees=exislow&labels=bug&projects=&template=bug.yml&title=%5BBug%5D+

I cannot re-produce this behavior with your limited information. If you cannot provide exact details, especially proven with screenshot I will close this issue soon.

**Comment by stork-afk** [comment]
> Regarding the settings, simply read the explanatory text here: https://github.com/exislow/tidal-dl-ng/issues/new?assignees=exislow&labels=bug&projects=&template=bug.yml&title=%5BBug%5D+
> 
> I cannot re-produce this behavior with your limited information. If you cannot provide exact details, especially proven with screenshot I will close this issue soon.

Thanks for your reply. Unfortunately, I still don't understand how to copy my settings. The link sends me to the bug report form and the only explanatory text I see is this one: 
Please copy and paste your settings from ~/.config/tidal_dl_ng/settings.json (macOS & Linux) 
I'm not code literate so I have no idea what that means. But thanks anyway I appreciate you doing the tidal-dl and I can use the gui with no problems, except that I am not able to see all my playlists created in Tidal, specially the new ones. 
Keep up the great work!

**Comment by stork-afk** [comment]
Hi! Just wanted to let you know the latest version  v0.15.6 fixed this issue. Thanks!
