### ISSUE TITLE
[Bug] column filtering not working for artist/album searches

### ISSUE THREAD

**Issue by loddar66** [exislow/tidal-dl-ng#130]
### What happened?

The column filtering is working for the 'track' search (although I couldn't find a suitable setting to filter for duration - thought about s.th. like '>04:00'...), but it does not show anything in the result list when filtering in 'artist' or 'album' mode.

![2024-06-15 11_31_56-TIDAL Downloader Next Generation!](https://github.com/exislow/tidal-dl-ng/assets/117679654/4a9bf676-0920-442d-9998-721caa4c7f18)
![2024-06-15 11_32_50-TIDAL Downloader Next Generation!](https://github.com/exislow/tidal-dl-ng/assets/117679654/5544e764-fd3c-480c-8a46-527e1beac72e)
![2024-06-15 11_33_26-TIDAL Downloader Next Generation!](https://github.com/exislow/tidal-dl-ng/assets/117679654/e4de3a0f-813d-433b-8283-73bbedfdce0b)

### Version App

v0.15.4

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "B:\\=Tidal=\\Downloader", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist}/[{album_year}] {album_title} [{album_id}] ({album_duration_minutes})/{album_track_num} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit} [{track_quality}]", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": true, "path_binary_ffmpeg": "C:\\Portable\\TidalDL-NG\\ffmpeg.exe", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by exislow** [comment]
Thanks for this report. The search is fixed now. You can use any regular expression. Currently it is not implemented to search for something like "> 6:00". But you can use the sort feature of the columns as a workaround. You are also free to open a feature request to be able to filter for track length greater time x or whatsoever. Maybe somebody will implement this.

**Comment by loddar66** [comment]
thank you for the quick fix - work like a charm 👍 Using RegEx is also fine - s.th. like `^[1-9]*` is already excluding almost all single tracks from the results
