### ISSUE TITLE
[Bug] Not all playlists being shown 

### ISSUE THREAD

**Issue by stefan2305** [exislow/tidal-dl-ng#131]
### What happened?

App seems limited in how many playlists are loaded.
Also seems to load playlists in order from Old to New, instead of New to Old (which if there needs to be a priority would be more useful). 
As such, nearly all of my more recent playlists of the last 2 years are missing.

Reloading, rebooting, etc. does not seem to help. Tested in GUI version. 

### Version App

v0.15.4

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": true, "lyrics_file": true, "video_download": true, "download_delay": true, "download_base_path": "E:\\Music\\TIDALDLNG", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": true, "path_binary_ffmpeg": "D:\\ffmpeg-7.0.1-full_build\\bin\\ffmpeg.exe", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by Evandro-GO** [comment]
This bug persists in version v0.15.6. All my playlists from a certain date does not show. I don't use directories for playlists. Running windows 11.

**Comment by Evandro-GO** [comment]
Since my new playlist are not being shown with v0.15.6, that is supposed to fix the bug, and this bug is not going to be solved, tidal-dl-ng is becoming useless. May be a have too much playlists. I don't know.
Returning to old tidal-dl that is still working (with some problems, as lyrics not sincronized) and looking for a paid solution that works flawlessly.

**Comment by ottworks** [comment]
Only the first 100 playlists are loaded

**Comment by Evandro-GO** [comment]
> Only the first 100 playlists are loaded

It shows only 50 of my playlists.

**Comment by exislow** [comment]
Is fixed and will be released soon.
