### ISSUE TITLE
[Feature] Create Playlists with symlinks

### ISSUE THREAD

**Issue by juxuanu** [exislow/tidal-dl-ng#133]
### Current Situation

Downloading a playlist creates a new folder and puts new track files in it, even though they may already exist in the Tracks folder already created when songs are downloaded separately.

### Suggestion / Feature Request

My suggestion is to always download into the Tracks folder, and the rest of the places where new song files would be downloaded to, should have symlinks created.

Example: say you want to download song ABC, which you have in two playlists and in your favourites. Right now, if I select both playlists and hit download list, I'll get `Playlists/{Playlis1,Playlist2}/ABC.flac`. If I now go into favourites, select the song ABC and hit download, I'll get a third copy of the song in `Tracks/`. 
So, it'd be extremely convenient if all songs downloaded into `Tracks/`, and each playlists I downloaded had `ABC.flac` in it as a (relative, so the whole file structure is movable) symlink to `../../Tracks/ABC.flac`.

**Comment by exislow** [comment]
Thank you for this idea. In my opinion this tool should stay a simple downloader without any library / management features. You hit the download button and the magic happens -- nothing less nothing more. Your idea brings a lot of "management" overhead to the code. I fully understand all the benefits but I would suggest you to create a script which is run after downloads are completed and do some clean up / management / linking work.

**Comment by juxuanu** [comment]
@exislow thanks for the work you put into this, it's extremely useful. I found one inconvenience, though: the symlinks created are not relative, but absolute. This means that if I download everything to ~/Music (~/Music/Tracks, ~/Music/Playlists, etc) and then want to move all of those subfolders to a different system, or to an SSD, etc, it won't work as the absolute paths of the links will be different.

I can try to take a look now and see if it's as simple as changing a parameter in a function call.

**Comment by juxuanu** [comment]
See https://github.com/exislow/tidal-dl-ng/pull/305

**Comment by exislow** [comment]
This makes sense. The symlinks should be relative. Thank you for your effort creating a possible solution. I have implemented this solution to address this issue, since it is easier and more trivial: https://github.com/exislow/tidal-dl-ng/commit/c0ca74811949d88158b6e6dbddf7cb54f8e0f543

**Comment by juxuanu** [comment]
@exislow the `.m3u` playlist files contain relative paths to the tracks in the main Tracks folder, which defeats the purpose of symlinking each song in each playlist folder.

Don't you think the playlist file should point to the files (links) in the same folder?

**Comment by exislow** [comment]
This could be a possible solution but this does not work with every music player. Some player do not like to get a playlist file pointing to symlinks (e.g. rekordbox). Also consider moving your collection from Linux to Windows. Windows links are different from Linux based links. With your approach the links and also the playlist file would be no usable. But with the implemented approach the playlist file still points to the specific items (so far in theory; have not tried it, yet).

**Comment by juxuanu** [comment]
Well I don't know about Windows support, but I guess it'd be expected that if you create unix symlinks, they wouldn't work on Windows.

Also, players bugging on symlinks doesn't seem to be a concern to this piece of software, from my point of view.

Anyway, I guess enabling both create a playlist and symlink songs in the playlist folder at the same time makes no sense, so I'll try to stick with one for now.

Thanks for your time and effort.
