### ISSUE TITLE
[Feature] Use ffmpeg package instead of binary

### ISSUE THREAD

**Issue by venttarc** [exislow/tidal-dl-ng#134]
### Current Situation

Currently, if we want to extract flac, we have to put the path of the binary file in the config. Which is great but a bit hassle. Here's a simple addition you can do;

### Suggestion / Feature Request

In linux based systems, instead of using the ffmpeg binary, why don't you utilise the installed ffmpeg package?(I am talking about CLI) It would be helpful and easier setup for lots of us.

**Comment by exislow** [comment]
If you already have the ffmpeg binary (which comes within a Linux package) installed, you do not need to re-install it. Just set the path to it in the config.
