### ISSUE TITLE
[Feature] Could the python request version be updated to 3.12?

### ISSUE THREAD

**Issue by PrincessOfHell** [exislow/tidal-dl-ng#135]
### Current Situation

I see that the requirements are python 3.11 and version 3.12 does not work.

### Suggestion / Feature Request

Python request version 3.12 compatibility.

**Comment by avibrazil** [comment]
Unless please provide a little guide on how to `pip install` the package for whom has Python 3.12, as me. Even if it won't work, just for testing.

**Comment by exislow** [comment]
Unfortunately this package https://pypi.org/project/pyqtdarktheme/ blocks the update to Python 3.11, since it depends officially on Python 3.11

There is already an issues raised for this: https://github.com/5yutan5/PyQtDarkTheme/issues/252

You can try to ask there as well. As soon as the dependency is update I will update this app.

**Comment by PrincessOfHell** [comment]
At the moment I have been able to get tidal-dl ng working by installing python 3.11 until they update pyqtdarktheme.  I will be waiting for the news.

**Comment by exislow** [comment]
If you need to have multiple Python versions installed, I would recommend to use `pyenv` (https://realpython.com/intro-to-pyenv/).

**Comment by ChilliGeologist** [comment]
> Unfortunately this package https://pypi.org/project/pyqtdarktheme/ blocks the update to Python 3.11, since it depends officially on Python 3.11
> 
> There is already an issues raised for this: [5yutan5/PyQtDarkTheme#252](https://github.com/5yutan5/PyQtDarkTheme/issues/252)
> 
> You can try to ask there as well. As soon as the dependency is update I will update this app.

Looking through the issue you linked it looks like a fix is sitting ready to merge which is frustrating. Someone has forked the repo however and included the fix to support python 3.12 and up: https://github.com/henriquegemignani/PyQtDarkTheme

Perhaps this could be used in place of the original one?

**Comment by exislow** [comment]
Done with https://github.com/exislow/tidal-dl-ng/commit/bffe6e56f1603ae75f0bef554ccec24d7055152d

**Comment by PrincessOfHell** [comment]
Ok...I will try it, thanks.
