### ISSUE TITLE
[Feature] Multithreading?

### ISSUE THREAD

**Issue by matteorizzo** [exislow/tidal-dl-ng#136]
### Current Situation

In the main page presentation image, I see a "Multithreading with maximum 12 threads" displayed in the console.
But I can't find that option in both Windows and Mac.

https://github.com/exislow/tidal-dl-ng/blob/master/assets/app.png

### Suggestion / Feature Request

It'd be great to be able to enable multi thread downloads.

**Comment by exislow** [comment]
I have removed this option, since TIDAL will block you quite fast if you start parallel download threads.

**Comment by Reasonable-Grape2698** [comment]
> I have removed this option, since TIDAL will block you quite fast if you start parallel download threads.

Anyway we can opt to reenable it at our own risk? I've used tidal-dl for months downloading at 1Gbps without a ban.
