### ISSUE TITLE
[Bug] Errors running tidal-dl-ng, tidal-dl-ng-gui

### ISSUE THREAD

**Issue by nakinigit** [exislow/tidal-dl-ng#139]
### What happened?

Installed on Linux Mint 21.3 Cinnamon via "pip install --upgrade tidal-dl-ng". Also  pip install --upgrade tidal-dl-ng[gui]. Trying to run tdng, tidal-dl-ng -v, or tidal-dl-ng-gui all give errors

### Version App

unknown

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/nk/.local/bin/tidal-dl-ng", line 5, in <module>
    from tidal_dl_ng.cli import app
  File "/home/nk/.local/lib/python3.10/site-packages/tidal_dl_ng/__init__.py", line 10, in <module>
    from tidal_dl_ng.constants import REQUESTS_TIMEOUT_SEC
  File "/home/nk/.local/lib/python3.10/site-packages/tidal_dl_ng/constants.py", line 1, in <module>
    from enum import StrEnum
```

### Your settings

```json
those folders do not exist
```

**Comment by vinhtq115** [comment]
You need to use Python 3.11. I also got the same error when using 3.10.

**Comment by exislow** [comment]
@nakinigit imcomplete details. Cannot re-produce it. Make sure, you are running Python 3.11
