### ISSUE TITLE
[Bug] when XDG_CONFIG_HOME set, config dir is ignored and new config generated in ~/.config/.config/tidal_dl_ng

### ISSUE THREAD

**Issue by mustaruhtinas** [exislow/tidal-dl-ng#141]
### What happened?

When XDG_CONFIG_HOME variable is set, tdn will not use the config located at ~/.config/tidal_dl_ng and instead will create a new .config/tidal-dl-ng dir inside the .config dir.

### Version App

0.15.6

### What operating system are you seeing the problem on?

Linux

### Your settings

```json
not relevant, since config is ignored anyway
```

**Comment by exislow** [comment]
Fixed.
