### ISSUE TITLE
[Help] Any way to set 2 digits for track number?

### ISSUE THREAD

**Issue by Exspecto322** [exislow/tidal-dl-ng#142]
### I need Help.

How to force 2 digits format for track numbers?

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "H:\\Music\\TidalDLTemp", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "{album_artist}/{album_title}/{album_track_num}. {artist_name} - {track_title}{track_explicit}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "{album_artist}/{album_title}/{album_track_num}. {artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "C:\\Users\\Administrator\\Documents\\ffmpeg-7.0.1-full_build\\bin\\ffmpeg.exe", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": true}
```

**Comment by exislow** [comment]
This function already sets the necessary leading digits / zeroes for `album_track_num`: https://github.com/exislow/tidal-dl-ng/blob/17390cba7c8276bef5b91f93eca0957ba7e9cbee/tidal_dl_ng/helper/path.py#L91-L95

What exactly is your idea? What do you need this for?

**Comment by Exspecto322** [comment]
I am using the exe for Windows, for me albums with less than 10 songs, will always be missing a 0, this happens with singles too
![image](https://github.com/exislow/tidal-dl-ng/assets/84108942/35e63507-84c1-4b6b-a8bd-c0a4978668ba)
only if the album has more than 10 songs they will all get double digits
![image](https://github.com/exislow/tidal-dl-ng/assets/84108942/7ab9cfb9-f887-47e4-b840-c26255cf2d95)
this makes it inconsistent, just wondering if there was a way to always have albums and singles named with two digits, from 01 to 09 instead of 1 to 9

**Comment by romner-set** [comment]
+1, I'd also prefer forcing 2-digit track numbers everywhere for consistency.

**Comment by ahuber86** [comment]
I am also having this same issue, using the Linux CLI version. I would also like a way to force the leading zero, or two-digit track number.

**Comment by loddar66** [comment]
> This function already sets the necessary leading digits / zeroes for `album_track_num`:
> 
> https://github.com/exislow/tidal-dl-ng/blob/17390cba7c8276bef5b91f93eca0957ba7e9cbee/tidal_dl_ng/helper/path.py#L91-L95
> 
> What exactly is your idea? What do you need this for?

maybe using something like "max(2, int(math.log10(num_tracks)) + 1)" would yield the desired result (minimum 2 digits, even if the number of tracks is below 10)

**Comment by Huber1** [comment]
+1 for consistency across the library

**Comment by exislow** [comment]
I have implemented this for albums. You can control the padding of `album_track_num` with the new config option `album_track_num_pad_min`.
