### ISSUE TITLE
[Bug] Not all playlists being shown

### ISSUE THREAD

**Issue by Evandro-GO** [exislow/tidal-dl-ng#145]
### What happened?

All my playlists from a certain date are not being shown. Only old playlists are listed. I don't use directories for playlists.

Version v0.15.6 is supposed to solve this problem, but it persists, at least, for windows version GUI. Running Windows 11.

### Version App

v0.15.6

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "T:\\", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "", "metadata_cover_dimension": "640", "extract_flac": false, "downgrade_on_hi_res": false}
```

**Comment by exislow** [comment]
Duplicate #131

**Comment by Evandro-GO** [comment]
Since my new playlist are not being shown with v0.15.6, that is supposed to fix the bug, and this bug is not going to be solved, tidal-dl-ng is becoming useless.
Returning to old tidal-dl that is still working (with some problems) and looking for a paid solution that works flawlessly.
