### ISSUE TITLE
[Feature] Add "Date Added" column for favorite tracks

### ISSUE THREAD

**Issue by ottworks** [exislow/tidal-dl-ng#146]
### Current Situation

I can't download newly-added favorite tracks, they're all lost in the jumble sorted by track title.

### Suggestion / Feature Request

Either add a date added column, or re-order the track number column to match date added, like the Tidal app does.

**Comment by exislow** [comment]
I will have a look into this.

**Comment by exislow** [comment]
Fixed with https://github.com/exislow/tidal-dl-ng/commit/ac7afca1bfbd255140602fb7863791b31cb4e109
