### ISSUE TITLE
[Feature] Search with Album / track id number tag

### ISSUE THREAD

**Issue by CodeMasterBlast** [exislow/tidal-dl-ng#150]
### Current Situation

When  you search for album / track

e.g.

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/956bb742-d6a7-4bd0-9795-66113afcf99f)

You have to scroll to find the exact album, sometimes there can be multiple releases with a few tracks that might be different. Then you'll look at the track list for each album to see which one your looking for. As well as this, there might be a release you are looking for which is a certain resolution etc.

Why not make it easier for the end user?

### Suggestion / Feature Request

When  you search for album / track in Tidal app in Windows 10 pro-

e.g.

https://tidal.com/browse/album/369883941?u

Would it be possible to use the ID **369883941** to search and download the exact track / album in the search. The drop down will have to be updated to show ID tag in drop down list (Artist, Album, Track, Video, Playlist, **ID Tag**)

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/79585649-ceaa-4799-b042-a6c1a1f5cff1)

This will ensure that the exact track / album is selected, instead of searching for the album / track from a list once the search is presented-

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/956bb742-d6a7-4bd0-9795-66113afcf99f)

**Comment by loddar66** [comment]
just try and paste the complete URL (like https://tidal.com/browse/album/369883941?u) into the search field...

![image](https://github.com/exislow/tidal-dl-ng/assets/117679654/761af3a0-55c8-4c93-8c6f-6c8075d37277)

**Comment by CodeMasterBlast** [comment]
Thanks loddar66.

I've also raised a feature request to do the reverse when you don't have the URL from Tidal. 

The scenario in this case is you look in your collection to find a specific album for a friend or you need to find the exact download etc. As the ID number is unique it solves other potential issues too-

https://github.com/exislow/tidal-dl-ng/issues/152

**Comment by exislow** [comment]
@CodeMasterBlast thanks for this well written feature request. It is not possible to only look for the ID (doesn't even work with the official TIDAL app). But as @loddar66 mentioned you need to use the full link, for instance, https://tidal.com/browse/album/369883941?u.
