### ISSUE TITLE
[Feature] Album / track id number tag, M for master, year of release incorporated in album title folder 

### ISSUE THREAD

**Issue by CodeMasterBlast** [exislow/tidal-dl-ng#152]
### Current Situation

Currently in the album title there is no album track id number tag and year of release

e.g.

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/c6213c4b-dd34-4132-a157-73adf4f3de76)

### Suggestion / Feature Request

It will be beneficial to have this information-

1) This is a unique number which is given to every album / single, this will ensure if a album / track isn't over written unless the exact same album / track is downloaded (with the same number tag). In some cases albums have the same title which might contain more or less tracks. If downloaded this will over write.
2) This track id number tag can be used quickly to search in Tidal desktop app to locate album / track etc.
3) Having the year of release in the folder gives, quick insight into when the album / track was released, without doing a deep dive into the metadata.

Example of album folder naming with master, explicit, track id / number tag and date-

Bitter Sweet Love (Deluxe)(Explicit) [369883941] [2023]

or even shorten 'Explicit' to E

Bitter Sweet Love (Deluxe)(E) [369883941] [2023]

or

[ME] Bitter Sweet Love (Deluxe) [369883941] [2023]

M= denotes Master recording
E= denotes Explicit
[369883941] denotes unique album  id
[2023]- release year

**Comment by exislow** [comment]
Have a look at this function: https://github.com/exislow/tidal-dl-ng/blob/17390cba7c8276bef5b91f93eca0957ba7e9cbee/tidal_dl_ng/helper/path.py#L65-L160

There is already an issue #70 which requests the explanation of all available placeholder. 

It has all you like, except of "Master Recording Tag". This information is currently not present in `tidal-python` library.

**Comment by CodeMasterBlast** [comment]
Hi,


"format_album": "Albums/{album_artist}/[{track_quality}{album_explicit}] {album_title}- [{album_id}] [{album_year}]/{track_volume_num}/{album_track_num} - {artist_name} - {track_title}"

**1) Album_id number**

The unique track / album number is the {album_id} in 'path.py'

I've added to the above and it brings the album_id back, this can be used in url below to share-

https://tidal.com/browse/album/<album_id>?u

**2) M for master**

This is track_quality in 'path.py' or 'audio_quality' in preferences. Having M for Master doesn't tell you very much when you look at the folder name. Having it as- 'LOW', 'HIGH', 'LOSSLESS','HI_RES', 'HIGH_RES_LOSSLESS' as it's shown GUI is the way to go. 

**3) Year of release**

The album_year in 'path.py'

So the album title folder now looks like-

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/67d19327-3816-41ee-a384-9521b3c679f9)

Thanks for your help, this enhancement request can now be closed.
