### ISSUE TITLE
[Feature] Takes long time to down load Albums

### ISSUE THREAD

**Issue by CodeMasterBlast** [exislow/tidal-dl-ng#153]
### Current Situation

To download albums can take 5 to 10 mins or longer!
This is not a ISP issue, just that the download process is extremely slow, I know about the 'download_delay' check box in the preferences. This doesn't make any difference, apart from leaving a delay in- between tracks resulting in taking even more time. I understand the purpose behind this feature.

I'm comparing to-

 https://github.com/yaronzz/Tidal-Media-Downloader

**For example:-**

Lets take- 

Dua Lipa track called Houdini which is 24Bit 44.1khz, 3m 5sec in duration from App

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/f595016a-4960-495d-931c-7fe5fbb7d641)

**Using Yaronzz downloader takes 13.11 seconds from pressing the download button to the track appearing in folder.**

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/df6072cc-37e0-45cf-a711-f72c83e70e17)

From Windows explorer-

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/9e1796d1-52dc-4c05-8ee9-1077346bfd86)

Inside folder-

![image](https://github.com/exislow/tidal-dl-ng/assets/158475392/920019c4-f86f-47a2-b431-5d3ddc09a9a6)

Using **Tidal-dl-ng takes 60 seconds for track appearing in folder.**

That is 60 - 13.11 sec

**Yaronzz app is 47 seconds approx. faster!**

### Suggestion / Feature Request

Investigate and understand bottle neck, 'Tune' code so that downloads are as fast as possible. Keep the 'download delay' feature as is.

**Comment by exislow** [comment]
Has probably to do with MPD streams (if HI_RES_LOSSLESS is used).

**Comment by exislow** [comment]
Fixed with https://github.com/exislow/tidal-dl-ng/commit/3bd66d60353efe672a1965edab5cdccd44345a53
