### ISSUE TITLE
Unable to download regular Hi-Res Flac

### ISSUE THREAD

**Issue by Macurta** [exislow/tidal-dl-ng#158]
### Current Situation

I am unable to download the regular flac files off of Tidal when choosing Hires lossless.

It downloads .m4a which to me is an unnecessary container. I'd rather have just the flac by itself. 
flac has more support than m4a. 

### Suggestion / Feature Request

The option for .m4a should be put in preferences and should not be forced. 

Please allow an option to download the regular flac file when downloading hi-res lossless. 

Add an option to choose .m4a for lossless and hi-res lossless download, allow to be optionable.

**Comment by Toastie** [comment]
This should already be possible using the "extract_flac" option in the preferences. You just have to have ffmpeg installed and provide its path to tidal-dl-ng.

**Comment by Macurta** [comment]
> This should already be possible using the "extract_flac" option in the preferences. You just have to have ffmpeg installed and provide its path to tidal-dl-ng.

Oh. Well. That works. Thanks.
