### ISSUE TITLE
[Bug] Unable to download HI_RES_LOSSLESS quality

### ISSUE THREAD

**Issue by olwe1** [exislow/tidal-dl-ng#162]
### What happened?

I'm unable to download HI_RES_LOSSLESS quality tracks. It's capped at 44.1khz 16bits on this 24 bits song: https://listen.tidal.com/album/20115556/track/20115560

I'm using CLI only

Here's my cfg: 
<img width="1430" alt="Capture d’écran 2024-07-22 à 23 30 39" src="https://github.com/user-attachments/assets/dd1e7c59-21fb-4d7b-8797-cc1c98b784ed">

Here's the track info:
<img width="1020" alt="Capture d’écran 2024-07-22 à 23 32 01" src="https://github.com/user-attachments/assets/cbfd25f5-1ef1-428b-b496-67045868eefa">

Thank you for your help and your amazing work!

Just a quick feedback: it'd be really nice to have the actual sound quality info while the songs are downloading, somewhere in that box 🙏
<img width="563" alt="Capture d’écran 2024-07-22 à 23 33 40" src="https://github.com/user-attachments/assets/9efd0d79-d106-4f35-970a-df8fbab4796f">

### Version App

0.15.6

### What operating system are you seeing the problem on?

Linux

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "/mnt/dietpi_data/data/jellyfin/Music", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "480", "format_album": "Albums/{album_artist}/{album_title}{album_explicit}/{album_track_num}. {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": true, "path_binary_ffmpeg": "", "metadata_cover_dimension": "320", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by romner-set** [comment]
Tidal is completely removing all MQA tracks today, this was one of those. Genuine 24-bit tracks (like https://tidal.com/browse/track/85236542) download just fine.

**Comment by olwe1** [comment]
It works with the song you provided but It's odd because I tried on two different songs that are supposed to be 24 bits. At least this is what is displayed on the tidal client 🤨
