### ISSUE TITLE
GUI: App and Try Icons not working

### ISSUE THREAD

**Issue by exislow** [exislow/tidal-dl-ng#17]
The app icon is not showing, whether in tray nor as app icon.

**Comment by exislow** [comment]
Fixed with 549931d142bf3904917b099f2c418ca982eb6d77.

**Comment by C-O-D** [comment]
I'm here on Manjaro / Cinnamon and I don't get the app to show the icon nor the name (defined in the desktop file) in the taskbar. Name is always tdng like the exec call and icon is a standard one. 
Can this be changed from your side?
