### ISSUE TITLE
[Bug] Contributing Artists not used for Album download

### ISSUE THREAD

**Issue by schaffer1969** [exislow/tidal-dl-ng#171]
### What happened?

Downloading an album consisting of various artists such as (https://tidal.com/browse/album/218141618?u).
If album is downloaded all file names have "Various Artists" used for {artist_name} and not contributing artists.

If album is expanded and songs selected, they download correctly into the "tracks" folder.

Expected outcome: When an album consists of various artists, the contributing artist tag should be used.

### Version App

v0.15.6

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "D:\\temp\\Lossless", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "C:\\Users\\me\\ffmpeg-7.0.2-essentials_build\\bin\\ffmpeg.exe", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by jookboks** [comment]
Is this fixed? I have the latest update and all the Christmas playlists I downloaded, and even single tracks I've downloaded, show the wrong album for the tracks and "Various Artists" as the artists

**Comment by exislow** [comment]
Cannot help you, if you do not provide exact details on how to re-produce your issue.

**Comment by jookboks** [comment]
I am not as proficient with GitHub and coding as the usual user likely is, so I may need some guidance to give you what you are looking for. When I search playlists and highlight the particular playlist I'm looking for and download, the files all go to one folder and when I look individually at the files, they all look like the metadata is correct. But when I open the playlist in Plexamp, only a few of the songs have tagged the artist correctly, and none of the album info is correct. Most of the songs are tagged as "Various Artists" I'm not sure if this is a problem with the way I have my folders setup or how they're downloading

**Comment by exislow** [comment]
Thanks for this general description. But I need to be able to exactly re-produce this. So you need to become more specific and provide exact / specific information. What did you download? Provide screenshots of what you just described etc. 

I mean, how would to describe your issue to somebody who are not you and does not know what you are talking about?

**Comment by jookboks** [comment]
Roger, when I get home I'll post something more informative. Thanks for your patience.
