### ISSUE TITLE
[Feature] Download 5.1 Content 

### ISSUE THREAD

**Issue by ryjayt** [exislow/tidal-dl-ng#173]
### Current Situation

When Downloading it only dose it in stereo. 

### Suggestion / Feature Request

The Only 2 ressons i wanted TIDLE over spotify was 5.1 content but its not suported on PC Would love to be able to download it. The other reson was higer quality audio over spotify

**Comment by exislow** [comment]
This should be implemented indeed. Feel free to get me a pull request for this.

**Comment by exislow** [comment]
I think its some sort of a duplicate of #106. If not, feel free to reopen this issue again.
