### ISSUE TITLE
[Bug] Not always showing highest available Quality on search

### ISSUE THREAD

**Issue by swekonfucius** [exislow/tidal-dl-ng#177]
### What happened?

While searching for albums the result is not always showing the highest available audio Quality, for example I searched for artist Yello and album Point, I can see two versions of Lossless, but if I search in Tidal (windows app or Roon) I see one Lossless flac (16, 44.1) and one Hi res (MQA 24, 48) version.

![tidalng](https://github.com/user-attachments/assets/f13db675-3554-42a9-ae83-c9ed79f0171f)
![roon](https://github.com/user-attachments/assets/ca62b40e-fb47-4a92-be60-51fbe980875e)

### Version App

v0.15.6

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": false, "download_delay": true, "download_base_path": "D:\\Shares\\Gemensam\\Music\\tidal_rips_ng", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "480", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "C:\\Users\\magnus\\Downloads\\ffmpeg-7.0.2-essentials_build\\ffmpeg-7.0.2-essentials_build\\bin\\ffmpeg.exe", "metadata_cover_dimension": "320", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by exislow** [comment]
Unfortunately I cannot re-produce that:

<img width="872" alt="Screenshot 2024-11-08 at 17 14 51" src="https://github.com/user-attachments/assets/8ad2017a-cf5c-4d1d-a3e1-edf517197520">

Do you still have this issue?

**Comment by exislow** [comment]
Stale
