### ISSUE TITLE
[Bug] tidal redirect url not showing up

### ISSUE THREAD

**Issue by tg4510** [exislow/tidal-dl-ng#179]
### What happened?

tidal redirect url not showing up help

### Version App

v0.15.6

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
cant get passed paste tidal redirect URL
```

**Comment by orbittwz** [comment]
did you try on different browser? did you cleared cache and cookies before using this?
your issue is missing some information, please improve it...

**Comment by exislow** [comment]
Closed due to stale.
