### ISSUE TITLE
[Feature] Multi-threaded downloads & download album covers

### ISSUE THREAD

**Issue by Thomas-Harrell** [exislow/tidal-dl-ng#180]
## Current Situation

- 💡 The CLI version is used, so the recommendations are based on this as well

- There is no multi-threaded download feature, and the current download speed is much slower than [Tidal-Media-Downloader](https://github.com/yaronzz/Tidal-Media-Downloader)

- No album art download

## Suggestion / Feature Request

- Add multi-threaded download option, maybe add [aria2](https://github.com/aria2/aria2) support

- Add option to download multiple audio tracks at the same time for downloading music from albums, playlists

- Add option to download album art, Select the resolution, image format, and image name for the album cover

- There's also a small point where, after I format the JSON file, when I run TIDAL-DL-NG, it re-scrambles the formatted JSON file

**Comment by exislow** [comment]
> * Add option to download album art, Select the resolution, image format, and image name for the album cover

This was partially addressed and fixed in #125 

> * There's also a small point where, after I format the JSON file, when I run TIDAL-DL-NG, it re-scrambles the formatted JSON file

Config file format handling is exclusive to this app. JSON configs will now be saved in a pretty formatted way. Fixed with https://github.com/exislow/tidal-dl-ng/commit/c985e50dc651ee055499bd0029579ce3bdca4793

**Comment by MarkD1212** [comment]
Thanks for a great program, I love the GUI. I would also appreciate if you could increase the download thread so 3. This is the same as Tidal Media Downloader. This program downloads a lot faster.

**Comment by exislow** [comment]
Multithreading has been implemented.
