### ISSUE TITLE
[Bug] Audio metadata missing: composers, album artists

### ISSUE THREAD

**Issue by Thomas-Harrell** [exislow/tidal-dl-ng#181]
## What happened?

- [https://tidal.com/browse/album/77607385](https://tidal.com/browse/album/77607385)

- Using the CLI Version

- Composer data is empty

- Album Artist is only the first one

- When I use Tidal-Media-Downloader to download, I can get the composer and full album artist information

## Version App

0.15.6 CLI

## What operating system are you seeing the problem on?

macOS

## Your settings

```json
Default Setting
```

**Comment by exislow** [comment]
Please open another issue with all the details needed to understand and re-produce this issue. Proofs and settings are missing.
