### ISSUE TITLE
[Bug] Audio Files less than 8 seconds do not download.

### ISSUE THREAD

**Issue by Compact42** [exislow/tidal-dl-ng#187]
### What happened?

Anytime an audio file using the downloader is under 8 seconds long, it will attempt to download the file, but will always error out, and refuse download.
The error in question: "'Logger' object is not callable".

### Version App

0.15.6

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
"'Logger' object is not callable".
```

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": true, "lyrics_file": true, "video_download": true, "download_delay": true, "download_base_path": "G:\\Tidal Music", "quality_audio": "LOSSLESS", "quality_video": "1080", "format_album": "Music/{album_artist} - {album_title} {album_explicit}/{album_track_num} {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Music/{album_artist} - {album_title} {track_explicit}/{album_track_num} {track_title}", "format_video": "Videos/{track_title} {track_explicit}", "video_convert_mp4": true, "path_binary_ffmpeg": "F:\\Val's Hell Resources\\ffmpeg-7.0.1-full_build\\bin\\ffmpeg.exe", "metadata_cover_dimension": "640", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by exislow** [comment]
Please provide all the details to be able to re-produce this issue.

**Comment by loddar66** [comment]
Tracks #6 and #8 of the 2nd part cannot be downloaded ("Logger object is not callable") in HI_RES
https://tidal.com/browse/album/305339144 

at least the queue doesn't seem to stop being processed in track mode...

If you are using the standard lossless version, it works without any issue
https://tidal.com/browse/album/187745235

![image](https://github.com/user-attachments/assets/628fb60c-6c2e-47e1-9b3b-5b0519674cb3)

**Comment by exislow** [comment]
Great details. Have fixed it with https://github.com/exislow/tidal-dl-ng/commit/600c2dda68b9b099c4335f481fe6d6af3f8e66b4

Thanks!
