### ISSUE TITLE
Adding Lyrics to stand-alone .lrc file

### ISSUE THREAD

**Issue by rgnet1** [exislow/tidal-dl-ng#19]
I'd like to have the ability to send the timed lyrics to dedicated file with the idnetial song name, just a different extension (.lrc)

ex: 01-song.flac 
     01-song.lrc

contents of the file is like:
[00:12.00]Line 1 lyrics
[00:17.20]Line 2 lyrics

These timed lyrics are already being pulled from tidal-dl-ng, just need to write it to the file, and add a config option for "lyricsfile : true/false" in the json config

**Comment by exislow** [comment]
I will try to implement this for the next release.
