### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by lanchbery** [exislow/tidal-dl-ng#192]
### I need Help.

[Errno 2] No such file or directory: "D:\\download\\Tracks\\Anne Schwanewilms, Vesko Eshkenazy, Netherlands Radio Choir, Prague Philharmonic Choir, Royal Concertgebouw Orchestra, Riccardo Chailly - Mahler Symphony No. 8 in E flat - Symphony of a Thousand - Part Two Final scene from Goethe's Faust Dir, der Un_.m4a"

![Untitled-1](https://github.com/user-attachments/assets/085e95f3-cd34-4486-bdc4-ce6492fa78a4)

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": false, "lyrics_file": true, "video_download": true, "download_delay": false, "download_base_path": "C:\\", "quality_audio": "LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "", "metadata_cover_dimension": "1280", "extract_flac": false, "downgrade_on_hi_res": false}
```

**Comment by loddar66** [comment]
did you try using a shorter file name? your example has more than 255 characters which can be an issue... you could (temporarily) e.g. remove the "artist_name" from the "format_track" definition.

**Comment by SPIKEYPUP** [comment]
> did you try using a shorter file name? your example has more than 255 characters which can be an issue... you could (temporarily) e.g. remove the "artist_name" from the "format_track" definition.

Agreed, the filename seems too long for Windows comfort, try to shorten the name of the destination file as suggested by Loddar66, I also wouldn't be shocked if all of that extreme punctuation and spacing is causing issues as well.

**Comment by exislow** [comment]
Please put more effort into the creation of issues: Chose a proper title.
