### ISSUE TITLE
[Help] Error when downloading

### ISSUE THREAD

**Issue by mikk64** [exislow/tidal-dl-ng#193]
### I need Help.

as stated, i get my url as indicated, and it seem logging in correctly, i see my tracks
but when downloading somethinng, anything, it gives me error: 
401 Client Error: Unauthorized for url
> 401 Client Error: Unauthorized for url: https://api.tidal.com/v1/tracks/384178541/playbackinfopostpaywall?sessionId=1d134435-03b5-44c3-92da-2db60a7c6cdb&countryCode=IT&limit=10000&playbackmode=STREAM&audioquality=HI_RES&assetpresentation=FULL

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "E:\\musica\\Album", "quality_audio": "HI_RES", "quality_video": "480", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "", "metadata_cover_dimension": "320", "extract_flac": false, "downgrade_on_hi_res": false}
```

**Comment by mikk64** [comment]
sorry, my mistake, it was logging to an old account, not working anymore
with the right one, everything is going wonderful! thanks!

**Comment by MiguelHernandezMontoya** [comment]
Hi there! I can't download any videos, can you help me please? this is the error message: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
