### ISSUE TITLE
[Help] First time running and I get this error

### ISSUE THREAD

**Issue by LegzRwheelz** [exislow/tidal-dl-ng#198]
### I need Help.

This is my first time running the program and I get this error when attempting to download a video. 
`'utf-8' codec can't decode byte 0x85 in position 34: invalid start byte`
I do not have a paid account yet, I am just testing out the program to get a feel for it before signing up. Is this related to the not having access to the service? Thanks guys.

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": true, "video_download": true, "download_delay": true, "download_base_path": "~/download", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": true, "path_binary_ffmpeg": "", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by loddar66** [comment]
![image](https://github.com/user-attachments/assets/bbd80738-cd1b-4db7-8f25-3f8996303775)

just go to 'preferences' and check 'extract_flac'...

**Comment by JBeebs528491** [comment]
I am using a paid Tidal account and tried enabling the 'extract_flac' preference, but all I get is the following error message:

> FFmpeg is not set. Videos can be downloaded but will not be processed. FLAC cannot be extracted from MP4 containers. Make sure FFmpeg is installed and the path to the binary is configured (`path_binary_ffmpeg`).

I have added FFmpeg as a Windows Environmental Variable, and PowerShell recognizes the installation, but it seems like Tidal DL NG is not recognizing it.

**Comment by loddar66** [comment]
it must be set in the program's preferences - at least this works perfectly here

![image](https://github.com/user-attachments/assets/c8a6646e-794f-444a-9eda-7e1e4a7872e3)
