### ISSUE TITLE
TIDAL-Downloader-NG.exe Crash

### ISSUE THREAD

**Issue by NoDowt** [exislow/tidal-dl-ng#2]
OS: Windows 11 23H2
TIDAL-Downloader-NG.exe - v0.4.31

Seems to randomly crash; sometimes at launch, sometimes when trying to download a file (and then re-launching & downloading same file doesn't crash).

Not sure if there is a log file with more info to include?
Event Viewer shows faulting module is different each time. Seems a mix of Qt6Gui.dll, ntdll.dll, VCRuntime140.dll

**Comment by exislow** [comment]
Thank you for the report. I will implement a logging functionality to file to be able to debug this better.

**Comment by Xayayia** [comment]
Happens to me to, but specifically when trying to download, example is A$AP Rocky - Sundress, the search shows 2 same results, one downloads, one crashes
