### ISSUE TITLE
TIDAL-Downloader-NG_windows-x64

### ISSUE THREAD

**Issue by NikolaZhechev** [exislow/tidal-dl-ng#20]
![Без име](https://github.com/exislow/tidal-dl-ng/assets/42648693/9f32d124-1b04-4428-bbc0-5ea6348f68ed)
The application does not start on Windows 11 Home.
I also tried to run as an administrator, but it still doesn't work.

**Comment by animusastralis** [comment]
I'm having a similar error with the following message: 

> Failed to execute script 'gui' due to unhandled exception: cannot access local variable 'settings_json' where it is not associated with a value

**Comment by exislow** [comment]
It's fixed with https://github.com/exislow/tidal-dl-ng/commit/a3473599316779b04a30de4a01bf893a68428219

Will be released as soon as this is merged: https://github.com/tamland/python-tidal/pull/221

**Comment by exislow** [comment]
I have released this fix. Get the newest version!
