### ISSUE TITLE
[Feature] Make artist_name be the main artist of the song

### ISSUE THREAD

**Issue by YaBoiMax** [exislow/tidal-dl-ng#200]
### Current Situation

The current `artist_name`  variable is the same as `album_artist`, which is annoying if you want to separate  songs into folders from different artists

### Suggestion / Feature Request

With `format_album` set to `{artist_name}/{album_title}/{album_track_num}. {track_title}`
Current it leads to this
![image](https://github.com/user-attachments/assets/5db6b25f-07b1-44db-94c1-656e447873ae)

When ideally it should be
![image](https://github.com/user-attachments/assets/9afc993e-7bda-4a90-919f-81120c0e7c07)

with the old folder structure self hosted music services like jellyfin or subsonic will not be able to properly index those artists/albums/songs due to limitations in the respective projects

**Comment by exislow** [comment]
Fixed with https://github.com/exislow/tidal-dl-ng/commit/02de0c81085ebc627daf60c5d259fad1056fb0e2

Please use this `{album_artist}/{album_title}/{album_track_num}. {track_title}` for  `format_album`.
