### ISSUE TITLE
[Bug] Random white noise in tracks?

### ISSUE THREAD

**Issue by YoonGSC** [exislow/tidal-dl-ng#203]
### What happened?

Hi, using the tool I got great results with some files but some downloaded with a very strong white noise added?
I figured that the tool is adding up the frequencies to match the max lossless quality I asked for? 
Am I using the tool wrong?

### Version App

v0.15.6

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": false, "download_delay": true, "download_base_path": "E:\\mix\\Playlist\\Octobre 2024\\test 2", "quality_audio": "HI_RES", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "", "metadata_cover_dimension": "320", "extract_flac": false, "downgrade_on_hi_res": false}```

**Comment by exislow** [comment]
I cannot help you if you do not provide a proof and details how to re-produce this.

**Comment by DamienAllbran** [comment]
I think this is an issue with TIDAL itself and not the program. TIDAL used MQA for its max lossless files for years before they changed over from FLAC, but it's been found that they pretty much converted the files and called it a day.
![Green Day - American Idiot(Explicit) flac](https://github.com/user-attachments/assets/326ef48a-b68a-4b52-894c-83e5a77a4902)
I downloaded a copy of American Idiot as FLAC, the line around 30kHz and the lines higher are a common sight for decoded MQA files. MQA has also been proven to be noisier than FLAC and can even add noise so unfortunately there is nothing that can be done until new hi-res lossless tracks are uploaded.

**Comment by exislow** [comment]
Thanks for this analysis. Shame on you, TIDAL! I will close this issue, since there is nothing we can do.

**Comment by YoonGSC** [comment]
thanks a lot for the explanation !
