### ISSUE TITLE
[Help] Downloads without tags, not able to tag them manually either 

### ISSUE THREAD

**Issue by tokr1** [exislow/tidal-dl-ng#204]
### I need Help.

Hello
I have got a problem with one of my tidal-dl-ng instances. Recently i have discovered that my tidal downloads are somehow corrupt, well the problem ist that they all are without tags. I can't even add the tags manually. When i am downloading the same file on a different machine (VM) all is fine. Also worth mentioning, that i can't expand the Artist/Album within the faulty tidal-dl-ng  anymore. 
I am on both machines on  0.15.6 and Manjaro 24.1.1. Settings within tidal-dl-ng are basically the same.
The one with the problem has received the latest manjaroOS updates, the other one not.
I am mentioning this because i assume tidal-dl-ng is just partially can be the problem. Or maybe even not at all?
Reinstall didn't change a thing.
Does anybody have an idea what the problem could be? Or maybe has an idea of how to figure the problem out?
 

### What operating system are you seeing the problem on?

Linux

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": false, "download_delay": true, "download_base_path": "~/download", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "480", "format_album": "Albums/{album_artist} - {album_title} - {album_year}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "/usr/bin/ffmpeg", "metadata_cover_dimension": "320", "extract_flac": true, "downgrade_on_hi_res": true}
```

**Comment by sibeliusg** [comment]
I have exactly the same issues on up to date Manjaro and Tidal-dl-ng 0.15.6 

I can add that VLC can open these flac files, but all other media players can't.

**Comment by C-O-D** [comment]
> I have exactly the same issues on up to date Manjaro and Tidal-dl-ng 0.15.6
> 
> I can add that VLC can open these flac files, but all other media players can't.

Exactly the same here.
Maybe it has something to do with a recent python-tidalapi 0.8 update? I can't find version 0.7.6 anywhere to cross-check...

**Comment by TheParaTiger** [comment]
you can execute `pip install python-tidalapi==0.7.6 --upgrade` to downgrade it if i'm right.

**Comment by C-O-D** [comment]
My installation is not a pip installation but from the AUR.
Maybe someone who has installed with pip can try it out?

**Comment by C-O-D** [comment]
Btw, I found out that the flac files are saved with wrong container files inzernally, so they look corrupt to some apps and therefore can't be tagged.
If you re-save them in an audio editor as flac's you will find that they work and are also tagged as usual...

**Comment by tokr1** [comment]
With python-tidalapi-0.8 the problem is definitely starting. 
Downgrading it to the earlier version python-tidalapi-0.7.6  fixed it again.

**Comment by exislow** [comment]
Please provide screenshots that proof what you have described. And also provide tracks, you have tried to download, so I can reproduce it.

**Comment by tokr1** [comment]
i am not sure what i can provide here...

![Screenshot_20241109_153221](https://github.com/user-attachments/assets/7b52fc41-2dee-461f-9430-a014d2842c4a)
here you can see that i am not able to unfold the artists songs

i can't even provide you with a file you could check . the search function doesn't seem to work for me anymore
![image](https://github.com/user-attachments/assets/a812ca35-6583-4050-9877-e1df4f1c7bea)
i hope that helps somehow?

Maybe someone else can provide a corrupt file?

**Comment by exislow** [comment]
You are using an unsupported Python version. Please read the README.md. You need to have Python3.11 and must not install `tidalapi` >= 0.8.0
