### ISSUE TITLE
[Help] 401 client error: unauthorized for url

### ISSUE THREAD

**Issue by PurpleRain12345** [exislow/tidal-dl-ng#209]
Edit: solved, used wrong account.

**Comment by KaloyanNaumov** [comment]
I'm trying to authenticate and after login, I'm getting a page:

Oops
We couldn't find the page you were looking for. Head back to our [homepage](https://tidal.com/) or try the links in the footer. If you need help, you can visit our [support pages](https://support.tidal.com/).

most likely it's related.

**Comment by PurpleRain12345** [comment]
@KaloyanNaumov No, that's normal. You put that link in the beginning screen and then it works.

**Comment by PurpleRain12345** [comment]
And if I try a different account, it says: utf-8' codec can't decode byte 0xe8 in position 63: invalid continuation byte

**Comment by exislow** [comment]
> I'm trying to authenticate and after login, I'm getting a page:
> 
> Oops We couldn't find the page you were looking for. Head back to our [homepage](https://tidal.com/) or try the links in the footer. If you need help, you can visit our [support pages](https://support.tidal.com/).
> 
> most likely it's related.

It's not. You should take your time and read the instruction properly, which the authorization screen of `tidal-dl-ng` provides.
