### ISSUE TITLE
PKCE authentication option

### ISSUE THREAD

**Issue by rockstar2020** [exislow/tidal-dl-ng#22]
Hi @exislow,
I see that you already contributed to python-tidal project by adding the option to authenticate via PKCE method. Well done!
Are you planning to add this option in your own project? 

Cheers

**Comment by exislow** [comment]
I have released this fix. Get the newest version!

**Comment by exislow** [comment]
If you are still logged in from a previous version of this app, you need to delete your current token and restart the app to be able to login with the new PKCE method.

Your token is located in `~/.config/tidal-dl-ng/token.json`.

**Comment by rockstar2020** [comment]
> If you are still logged in from a previous version of this app, you need to delete your current token and restart the app to be able to login with the new PKCE method.
> 
> Your token is located in `~/.config/tidal-dl-ng/token.json`.

That's wonderful!
I'll give it a try later today.

**Comment by rockstar2020** [comment]
OK, I just tried it and login went through smoothly but when downloading a track I get this error message:
AttributeError: 'Track' object has no attribute 'stream'

**Comment by rockstar2020** [comment]
Thanks a lot, it's working now, but why is the extension m4a. Shouldn't it be flac?!!!
Am I missing anything in the settings?
Also, when downloading albums the folder name is populating the artist name correctly but not the album name.
For example the folder name for the album "Wall Of Eyes" from the artist "The Smile" is created as: <The Smile - {album_name}>.
What I have in settings for album folder is: 
"format_album": "{artist_name} - {album_name}/{track_num}. {artist_name} - {track_title}"

Cheers

**Comment by rockstar2020** [comment]
OK, I figured it out.
The format of the folder in your settings should be {album_title} whereas it was by default {album_name}.
But still I don't know why the extension is m4a and also the metadata doesn't seem right.
It would be great if you could double check from your side as well.

**Comment by exislow** [comment]
MP4/M4A is just a container format, which can contain, for instance, audio files encoded with aac, mp3 and flac, see https://de.wikipedia.org/wiki/MP4

If you are on linux you can just use `file <file>` or something like this or on mac `afinfo <file>` to get more information about the file. The extension doesn't say anything about the true content / encoding of the file. Thus, an MP4 container file can actually have a FLAC encoded audio track inside.

Nevertheless, the tool saves the files as it gets them from TIDAL. Some have the extension MP4 / M4A some have MP3 or FLAC. Please also have a look at: https://tidal.com/sound-quality It says, you can get the quality UP TO something. Not everything is in the highest quality available at TIDAL. No there is no guarantee at all for the quality. It is all depending on TIDAL, what version they have of the song. You are only telling them, that the highest quality you like to have is, for example, HiRes. If the track is available in this option, they will provide this file, otherwise the next best version will be provided. This can be 16bit FLAC, or MQA or only 320k MP3. Its up to them. And, of course, you need to have the correct subscription.

I hope that clarified your confusion.

**Comment by rockstar2020** [comment]
> MP4/M4A is just a container format, which can contain, for instance, audio files encoded with aac, mp3 and flac, see https://de.wikipedia.org/wiki/MP4
> 
> If you are on linux you can just use `file <file>` or something like this or on mac `afinfo <file>` to get more information about the file. The extension doesn't say anything about the true content / encoding of the file. Thus, an MP4 container file can actually have a FLAC encoded audio track inside.
> 
> Nevertheless, the tool saves the files as it gets them from TIDAL. Some have the extension MP4 / M4A some have MP3 or FLAC. Please also have a look at: https://tidal.com/sound-quality It says, you can get the quality UP TO something. Not everything is in the highest quality available at TIDAL. No there is no guarantee at all for the quality. It is all depending on TIDAL, what version they have of the song. You are only telling them, that the highest quality you like to have is, for example, HiRes. If the track is available in this option, they will provide this file, otherwise the next best version will be provided. This can be 16bit FLAC, or MQA or only 320k MP3. Its up to them. And, of course, you need to have the correct subscription.
> 
> I hope that clarified your confusion.
> 
> Thanks for mentioning the issue with `{album_name}`. This was changed some releases ago. I guess your config has been created by one of the very early releases of this app and has been never updated. New creating configs will have the correct default value.

Thanks for the detailed explanation.
I'm aware of everything you said but when I analyzed the downloaded file with m4a extension, I can see the format is FLAC. 
All I'm saying it's that the extension should match the format shown in the container.
I hope it makes sense.

FYI, I downloaded the same track in Hi-Res quality with Tidal-Music-Downloader (Yaronzz) and the file size and bitrate is exactly the same but with flac extension.

Just thought of reporting the issue. Up to you to looking into it.

Thanks for the great work.

**Comment by exislow** [comment]
> Thanks for the detailed explanation. I'm aware of everything you said but when I analyzed the downloaded file with m4a extension, I can see the format is FLAC. All I'm saying it's that the extension should match the format shown in the container. I hope it makes sense.

As you said, it is a container, thus the extension must match the container itself, not the content. Different example: MKV is a container format as well, it can contain, for instance audio tracks and h.264 encoded video tracks. Why are all these files have `*.mkv` as the extension and not something else?

Can you use `afinfo`? If not, just tell me the TIDAL link to the track you are wondering about and the used audio quality and I will paste you the output of `afinfo`, which will proof my explanation.

> FYI, I downloaded the same track in Hi-Res quality with Tidal-Music-Downloader (Yaronzz) and the file size and bitrate is exactly the same but with flac extension.

I am aware of this. The code shows, that Tidal-Music-Downloader (Yaronzz) doesn't pay attention to the actual file format. He sets extensions on best guesses, which is not correct.

**Comment by rockstar2020** [comment]
I'm using a software called Mediainfo (https://mediaarea.net/en/MediaInfo/Download) to analyze my files. Also, I use a software called Lossless Audio Checker (https://losslessaudiochecker.com/) to ensure the flac file is truly lossless
Below is the snapshot of the track (https://tidal.com/browse/track/327843446) which I downloaded with your tool:
![image](https://github.com/exislow/tidal-dl-ng/assets/35903046/b8e987d6-cab7-4262-abf3-11498b1cf631)

As you can see the audio codec in the container is FLAC.

But when I rename the extension from m4a to FLAC and use lossless audio checker software, I get FLAC error. This confirms what you said above which I think is because of MQA effect of the audio stream.
However, if I download the same file using Yaronzz tool which outputs a FLAC file (though it's only 44/16), it's showing as true lossless flac.

I believe this has something to do with MQA.
I'll do some more digging and will keep you posted.

Cheers

**Comment by exislow** [comment]
Okay, once again: Please read this https://de.wikipedia.org/wiki/MP4
It doesn't make sense to continue this discussion, before you haven't understood the concept of a container format.

I also cannot help you, if you won't show me your config file, or at least (as requested) your audio quality settings. Nevertheless, if this tool downloads this track https://tidal.com/browse/track/327843446 and saves it as a `*.flac` file, since TIDAL is not providing a container here but a true FLAC file (see line "File Type ID"):

```bash
afinfo Peter\ Gabriel\ -\ The\ Court\ \(Bright-Side\ Mix\).flac
File:           Peter Gabriel - The Court (Bright-Side Mix).flac
File type ID:   flac
Num Tracks:     1
----
Data format:     2 ch,  48000 Hz, flac (0x00000003) from 24-bit source, 4096 frames/packet
Channel layout: Stereo (L R)
estimated duration: 261.032875 sec
audio bytes: 56433593
audio packets: 3059
bit rate: 1729535 bits per second
packet size upper bound: 22465
maximum packet size: 22465
audio data file offset: 73223
optimized
audio 12529578 valid frames + 0 priming + 86 remainder = 12529664
source bit depth: I24
----
```

Send me your file (upload it somewhere but not here) and I can perform an `afinfo` check for you.

**Comment by rockstar2020** [comment]
> Okay, once again: Please read this https://de.wikipedia.org/wiki/MP4
> It doesn't make sense to continue this discussion, before you haven't understood the concept of a container format.
> 
> I also cannot help you, if you won't show me your config file, or at least (as requested) your audio quality settings. Nevertheless, if this tool downloads this track https://tidal.com/browse/track/327843446 and saves it as a `*.flac` file, since TIDAL is not providing a container here but a true FLAC file (see line "File Type ID"):
> 
> ```bash
> afinfo Peter\ Gabriel\ -\ The\ Court\ \(Bright-Side\ Mix\).flac
> File:           Peter Gabriel - The Court (Bright-Side Mix).flac
> File type ID:   flac
> Num Tracks:     1
> ----
> Data format:     2 ch,  48000 Hz, flac (0x00000003) from 24-bit source, 4096 frames/packet
> Channel layout: Stereo (L R)
> estimated duration: 261.032875 sec
> audio bytes: 56433593
> audio packets: 3059
> bit rate: 1729535 bits per second
> packet size upper bound: 22465
> maximum packet size: 22465
> audio data file offset: 73223
> optimized
> audio 12529578 valid frames + 0 priming + 86 remainder = 12529664
> source bit depth: I24
> ----
> ```
> 
> Send me your file (upload it somewhere but not here) and I can perform an `afinfo` check for you.

It's clear now.
Thanks for taking time to further elaborate on it.
Cheers
