### ISSUE TITLE
[Bug]  The program forms an infinite loop

### ISSUE THREAD

**Issue by JJ110112** [exislow/tidal-dl-ng#228]
### What happened?

The steps to reproduce the problem are as follows:

1. From Tidal, add following playlist: "Indie: Headphone Classics", "Jazz: Headphone Classics", "K-Pop: Headphone Classics"
2. Download playlists in [tidal-dl-ng]
3. error message: 
    (1) "[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2580)"
     (2) "This track is not available for listening anymore on TIDAL. Skipping: Loco, Hwa Sa - Somebody!"
     (3) "This track is not available for listening anymore on TIDAL. Skipping: 4Men, MIIII - 그 남자 그 여자"
4. After that, the program is stuck in the loop of "K-Pop: Headphone Classics" and cannot download the subsequent playlist.

The program will continuously download the playlist "K-Pop: Headphone Classics" and log the message "Download skipped, since file exists: ..." forever.

<img width="1152" alt="error" src="https://github.com/user-attachments/assets/e73bfcda-c9c0-4798-910f-db7b2e43c8f0">
[log.txt](https://github.com/user-attachments/files/17730152/log.txt)

### Version App

v0.15.6

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
log file too big, please see the attached file.
```

### Your settings

```json
{"skip_existing": "extension_ignore", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "C:\\Music\\Loseless", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "E:\\Softwares\\ffmpeg-2024-11-06-git-4047b887fc-full_build\\bin\\ffmpeg.exe", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by sujay1599** [comment]
yeh vcan't even download track or you can some but fails on videos

**Comment by exislow** [comment]
This is fixed with the current `master` (https://github.com/exislow/tidal-dl-ng/tree/c75edc9b6ba3821f295e057ffd3972bcd5142b55) and will be released soon.

**Comment by JJ110112** [comment]
Amazing! You are awesome!
Thanks!  ^_^

exislow ***@***.***> 於 2024年11月13日 週三 19:47 寫道：
