### ISSUE TITLE
[Feature] Adding album_year feasible?

### ISSUE THREAD

**Issue by ni-pa-ny** [exislow/tidal-dl-ng#234]
### Current Situation

album year not supported

### Suggestion / Feature Request

adding to the settings menu the option to add also the album year for folder output like:

`Albums/{album_year} - {album_title}{album_explicit}/{album_track_num} - {track_title}`

**Comment by exislow** [comment]
`{album_year}` is already supported, see https://github.com/exislow/tidal-dl-ng/blob/6f112546a515b67b3964d4164fca703d68e38610/tidal_dl_ng/helper/path.py#L138-L142

What's wrong with that?

**Comment by ni-pa-ny** [comment]
oh - blame me, did not know that its already supported :-)
thnaks for your work bro!
