### ISSUE TITLE
[Feature] Qt Version < 6.8

### ISSUE THREAD

**Issue by regorxxx** [exislow/tidal-dl-ng#236]
### Current Situation

This is probably not high priority, but last version built with 6.8.3 is no longer compatible in any way with win 7.

QT6 can be patched with this:
https://github.com/crystalidea/qt6windows7

And any missing win 10 method with this:
https://github.com/i486/VxKex

That approach was working fine up to Qt 6.7.1 which was the version used at 0.15.6. (in fact just using VxKex worked fine). Newer versions refuse to execute in any way due to Qt 6.8.3 usage.

### Suggestion / Feature Request

Would it be possible to offer a version built with Qt 6.7.1 or 6.7.3 again? It would be much appreciated (and I understand it's not a solution in the long term).

**Comment by odyn1982** [comment]
I confirm that I also cannot open new versions of the application on Windows 10 LTSB 1607
"Traceback (most recent call last):
  File "tidal_dl_ng\gui.py", line 6, in <module>
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found."
![Unhandled exception in script](https://github.com/user-attachments/assets/87e002a7-d3d4-4b17-b353-2e3f21abb3e0)
![WINDOWS](https://github.com/user-attachments/assets/45a2199e-7bb4-4e44-b1bc-b1d3fcab29c5)

**Comment by exislow** [comment]
What a mess with Qt. Thank you for reporting this. I will have a look into this.

**Comment by regorxxx** [comment]
Checked this and no version has worked after this fix.

As far as I know these are the compatible versions:
https://github.com/crystalidea/qt6windows7
Qt6.8.0, Qt6.8.1, Qt6.7.3. (if one of these are used, and they don't work, at least I can create an issue about it there)

Qt6.7.1 seemed to work fine with [VxKex](https://github.com/i486/VxKex), no idea why 6.7.0 doesn't work. 

But for some reason the version used now doesn't work with any of those workarounds.
