### ISSUE TITLE
[Bug] tracks are downloaded with .m4a extension instead of .flac

### ISSUE THREAD

**Issue by stork-afk** [exislow/tidal-dl-ng#237]
### What happened?

Tracks downoalded with v0.20.2 and v0.20.3 are saved with a .m4a extension instead of .flac
This happens when downloading both playlists and individual tracks
I'm sorry but I can't find the settings file so I'm attaching a photo of my settings.

<img width="637" alt="Screenshot 2024-11-15 at 14 43 00" src="https://github.com/user-attachments/assets/036f3fb3-5021-48b1-8996-083b3616afdd">

### Version App

v0.20.3

### What operating system are you seeing the problem on?

macOS

### Your settings

```json
.
```

**Comment by ryoko7** [comment]
Likely a side effect of a hotfix in v0.20.2 (PR #233 ) *or* part of the known upstream bug.
[Exislow's fix ](https://github.com/tamland/python-tidal/pull/305) for tidalapi issue [304 ](https://github.com/tamland/python-tidal/issues/304) has not been merged yet. 
At that point, the hotfix will be removed.

**Comment by loddar66** [comment]
did you already try downloading with the option "extract_flac" enabled?

**Comment by exislow** [comment]
@stork-afk: Try to supply all necessary field / information next time and please read the option description.
