### ISSUE TITLE
Virus detected??

### ISSUE THREAD

**Issue by Notorious2Beat** [exislow/tidal-dl-ng#238]
### What happened?

When downloading windows get a pop up saying virus detected 

### Version App

v0.20.3

### What operating system are you seeing the problem on?

None

### Your settings

```json
Just tried downloading it
```

**Comment by ryoko7** [comment]
Duplicate, see #231

**Comment by lkjdsf65** [comment]
![Uploading Captura de pantalla 2024-11-30 221436.png…]()

**Comment by lkjdsf65** [comment]
![image](https://github.com/user-attachments/assets/0cd4acd7-b293-4bb2-a426-255182dcef33)
