### ISSUE TITLE
[Bug] {album_artist} for format_track of cfg is not working properly

### ISSUE THREAD

**Issue by karlbishnu** [exislow/tidal-dl-ng#239]
### What happened?

I set format_track as "{album_artist}/{album_title}/{album_track_num}. {artist_name} - {track_title}".
But it made a directory named as "{album_artist}" not album_artist in tag.
![image](https://github.com/user-attachments/assets/a1cf8eaa-f442-4523-baa9-a71578a4697e)

### Version App

v0.20.3

### What operating system are you seeing the problem on?

macOS

### Your settings

```json
{
    "skip_existing": true,
    "lyrics_embed": true,
    "lyrics_file": false,
    "video_download": true,
    "download_delay": true,
    "download_base_path": "/Users/karlbishnu/nas/Tidal/Album",
    "quality_audio": "HI_RES_LOSSLESS",
    "quality_video": "1080",
    "format_album": "{album_artist}/{album_title}/{album_track_num}. {artist_name} - {track_title}",
    "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}",
    "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}",
    "format_track": "{album_artist}/{album_title}/{album_track_num}. {artist_name} - {track_title}",
    "format_video": "{album_artist}/{album_title}/{album_track_num}. {artist_name} - {track_title}",
    "video_convert_mp4": true,
    "path_binary_ffmpeg": "/opt/homebrew/Cellar/ffmpeg/7.1_3/bin/ffmpeg",
    "metadata_cover_dimension": "1280",
    "metadata_cover_embed": true,
    "cover_album_file": true,
    "extract_flac": true,
    "downloads_simultaneous_per_track_max": 20
}
```

**Comment by exislow** [comment]
Please post a link to an album, where this happens.

**Comment by cyw0204** [comment]
Can you teach me why some songs are not downloaded?
These songs are recorded in My Favorites Tracks and play normally online on Tidal.

> Next download will start in 2.3 seconds.
> 'NoneType' object has no attribute 'first_url'
> Next download will start in 3.6 seconds.
> Next download will start in 2.2 seconds.
> Next download will start in 3.7 seconds.
> 'NoneType' object has no attribute 'first_url'

Thank you for teaching me.
I always use it well.
I hope you are always healthy and happy.^^

**Comment by karlbishnu** [comment]
Hi @exislow 
Here: https://tidal.com/browse/track/315337767\?u

**Comment by exislow** [comment]
Fixed with https://github.com/exislow/tidal-dl-ng/commit/91244c0936d8c41a99b33b1cab90b8a42d68b306

Thank you for reporting this issue.
