### ISSUE TITLE
Set download path, quality and url all in one CLI command

### ISSUE THREAD

**Issue by rockstar2020** [exislow/tidal-dl-ng#24]
Hi @exislow,
I know you are quite busy working on adding PKCE login method to your next release, which I'm so eagerly waiting for, but still wanted to ask if you could consider adding a feature in your CLI command to set the download path, quality and url(s) all in one line.
For example, something like:
tidal-dl-ng cfg download_base_path "/mnt/test/" quality "Hi-Res" dl https://tidal.com/browse/track/xxxxxxxxxx

Thanks in advance

**Comment by exislow** [comment]
Hey. Thank you for your request. So you basically like to have different location and quality settings per song download? Do I get your request right?

**Comment by rockstar2020** [comment]
> Hey. Thank you for your request. So you basically like to have different location and quality settings per song download? Do I get your request right?

That's absolutely correct.
Thank you!

**Comment by exislow** [comment]
What is the pain, if you are doing it this way for every dl?

```bash
tidal-dl-ng cfg download_base_path "/mnt/test/"
tidal-dl-ng cfg quality "Hi-Res" dl https://tidal.com/browse/track/xxxxxxxxxx
tidal-dl-ng dl https://tidal.com/browse/track/xxxxxxxxxx
```

**Comment by rockstar2020** [comment]
> What is the pain, if you are doing it this way for every dl?
> 
> ```bash
> tidal-dl-ng cfg download_base_path "/mnt/test/"
> tidal-dl-ng cfg quality "Hi-Res" dl https://tidal.com/browse/track/xxxxxxxxxx
> tidal-dl-ng dl https://tidal.com/browse/track/xxxxxxxxxx
> ```

Well, it's 3 lines of commands versus 1 line. :)
I just suggested cause it makes more sense.

**Comment by exislow** [comment]
That's right. But you could transform this into a one liner, like this:


```bash
tidal-dl-ng cfg download_base_path "/mnt/test/" && tidal-dl-ng cfg quality "Hi-Res" dl https://tidal.com/browse/track/xxxxxxxxxx && tidal-dl-ng dl https://tidal.com/browse/track/xxxxxxxxxx
```

Anyway, I will put this on the road map as low priority, if you don't mind.

**Comment by rockstar2020** [comment]
Are you sure the cfg command works?
I get the following message when I run:
tidal-dl-ng cfg quality "Hi-Res"

Option "quality" is not valid!

**Comment by rockstar2020** [comment]
Nevermind, the correct command is:
tidal-dl-ng cfg quality_audio "Hi-Res"

It should be quality_audio not quality.
Cheers

**Comment by exislow** [comment]
> Nevermind, the correct command is: tidal-dl-ng cfg quality_audio "Hi_Res_Lossless" It should be quality_audio not quality.

That's correct. I actually just copied your text and worked with that.

> For some reason "Hi_Res" quality doesn't work and the tool automatically changes the settings.json file to "High".

It works in my case, but I use "HI_RES". Maybe it's case sensitive. The values should match these values: https://github.com/tamland/python-tidal/blob/master/tidalapi/media.py#L40-L45
