### ISSUE TITLE
[Feature]  Add ReplayGain information

### ISSUE THREAD

**Issue by mono66985** [exislow/tidal-dl-ng#240]
### Current Situation

ReplayGain information is missing.

### Suggestion / Feature Request

If it's not too much trouble for you, could you please also include the ReplayGain information when downloading using the GUI downloader. It's sometimes necessary for me.

**Comment by exislow** [comment]
Do you know the correct MP3, FLAC and MP4 tag / frame names for replay gain information?

**Comment by mono66985** [comment]
I'm sorry, I don't know exactly what part you need, but I think someone else's previous post has some info on this, maybe that will help?

https://github.com/exislow/tidal-dl-ng/issues/35#issuecomment-1928913091

  tidal-dl-ng dl https://tidal.com/browse/track/152668960
Let us check, if you are already logged in... Yep, looks good! You are logged in.
{'session': <tidalapi.session.Session object at 0x7915d427b110>, 'requests': <tidalapi.request.Requests object at 0x7915d427aed0>, 'album': <tidalapi.album.Album object at 0x7915d4383f50>, 
'id': 152668960, 'name': 'All Of Me', 'duration': 163, 'available': True, 'tidal_release_date': datetime.datetime(2020, 8, 28, 0, 0, tzinfo=tzutc()), 'user_date_added': None, 'track_num': 2,
'volume_num': 1, 'explicit': False, 'popularity': 14, 'artist': <tidalapi.artist.Artist object at 0x7915d45da910>, 'artists': [<tidalapi.artist.Artist object at 0x7915d45d9110>, 
<tidalapi.artist.Artist object at 0x7915d45d8fd0>], 'type': None, 'artist_roles': None, 'replay_gain': -10.59, 'peak': 0.999937, 'isrc': 'USUM72014229', 'copyright': '℗ 2020 Republic 
Records, a division of UMG Recordings, Inc.', 'audio_quality': <Quality.hi_res: 'HI_RES'>, 'version': None, 'media_metadata_tags': ['LOSSLESS', 'MQA'], 'full_name': 'All Of Me'}
{'session': <tidalapi.session.Session object at 0x7915d427b110>, 'requests': <tidalapi.request.Requests object at 0x7915d427aed0>, 'artist': <tidalapi.artist.Artist object at 
0x7915d45d9110>, 'id': 152668956, 'cover': '38201f9b-fb1e-45df-b4fa-85464bf4df6e', 'video_cover': None, 'duration': None, 'available': None, 'num_tracks': None, 'num_videos': None, 
'num_volumes': None, 'copyright': None, 'version': None, 'explicit': None, 'universal_product_number': None, 'popularity': None, 'type': None, 'artists': [<tidalapi.artist.Artist object at 
0x7915d45d9110>, <tidalapi.artist.Artist object at 0x7915d45d8fd0>], 'release_date': None, 'tidal_release_date': None, 'user_date_added': None}

'replay_gain': -10.59, 'peak': 0.999937 parts.

**Comment by exislow** [comment]
This is not helpful. My question is: Where is the replay gain information missing?

**Comment by exislow** [comment]
Great, this was the information I was missing. But this is only the name for ID3v2 metadata, which is only used for MP3 files. We need the equivalent for FLAC and MP4 containers. Do you now what to use for the missing to formats?

**Comment by mono66985** [comment]
Not using the same name? When I checked using Mp3tag, they are stored as 'REPLAYGAIN_TRACK_GAIN, REPLAYGAIN_TRACK_PEAK' even in FLAC (FLAC) tags. It is the same when using foobar2000.

**Comment by mono66985** [comment]
https://xiph.org/flac/documentation_tools_metaflac.html

--add-replay-gain
    Calculates the title and album gains/peaks of the given FLAC files as if all the files were part of one album, then stores them as FLAC tags. The tags are the same as those used by vorbisgain. Existing ReplayGain tags will be replaced. If only one FLAC file is given, the album and title gains will be the same. Since this operation requires two passes, it is always executed last, after all other operations have been completed and written to disk. All FLAC files specified must have the same resolution, sample rate, and number of channels. Only mono and stereo files are allowed, and the sample rate must be 8, 11.025, 12, 16, 18.9, 22.05, 24, 28, 32, 36, 37.8, 44.1, 48, 56, 64, 72, 75.6, 88.2, 96, 112, 128, 144, 151.2, 176.4, 192, 224, 256, 288, 302.4, 352.8, 384, 448, 512, 576, or 604.8 kHz.

https://manpages.ubuntu.com/manpages/focal/en/man1/vorbisgain.1.html

       vorbisgain creates tags like these (when in -a mode):

              REPLAYGAIN_TRACK_GAIN=-7.03 dB
              REPLAYGAIN_TRACK_PEAK=1.21822226
              REPLAYGAIN_ALBUM_GAIN=-6.37 dB
              REPLAYGAIN_ALBUM_PEAK=1.21822226

From what I've found, they seem to use the same name.

**Comment by exislow** [comment]
This sounds great. So, only the information for MP4 (M4A) is missing.

**Comment by exislow** [comment]
> * https://mutagen.readthedocs.io/en/latest/api/mp4.html#mutagen.mp4.MP4Tags

As shown here, you cannot use such a long tag identifier for MP4.

**Comment by mono66985** [comment]
I tried searching again, but I didn't find a document about the replay gain on the MP4.
It's an expedient, but if you use the same tag as FLAC, most players recognize it. Too bad it's not a clear way.
I'd like to see FLAC support replay gain in the next version, even if MP4 can't.
Thank you for your hard work.
