### ISSUE TITLE
[Help] album_artist and cover for single Track

### ISSUE THREAD

**Issue by Huber1** [exislow/tidal-dl-ng#250]
### I need Help.

Hello,
my case is downloading single tracks. I still need them in the Artist/Album/Song.flac format in case i download more songs later.
Is there a way to get the album artist when downloading single tracks? Else the album folder is created inside every artist folder separately if multiple artists collaborate.
Also is it possible to download the album cover when downloading a single track?
Greetings

### What operating system are you seeing the problem on?

Linux

### Your settings

```json
{
    "skip_existing": true,
    "lyrics_embed": true,
    "lyrics_file": false,
    "video_download": true,
    "download_delay": true,
    "download_base_path": "/home/rocky/media/tidal",
    "quality_audio": "LOSSLESS",
    "quality_video": "720",
    "format_album": "{album_artist}/{album_title} [{album_year}]/{album_track_num} {artist_name} - {track_title}{track_explicit}",
    "format_playlist": "{album_artist}/{album_title} [{album_year}]/{album_track_num} {artist_name} - {track_title}{track_explicit}",
    "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}",
    "format_track": "{album_artist}/{album_title} [{album_year}]/{album_track_num} {artist_name} - {track_title}{track_explicit}",
    "format_video": "Videos/{artist_name} - {track_title}{track_explicit}",
    "video_convert_mp4": false,
    "path_binary_ffmpeg": "/home/rocky/scripts/ffmpeg",
    "metadata_cover_dimension": "1280",
    "metadata_cover_embed": true,
    "cover_album_file": true,
    "extract_flac": true,
    "downloads_simultaneous_per_track_max": 20
}
```

**Comment by exislow** [comment]
See 

* https://github.com/exislow/tidal-dl-ng/issues/125
* https://github.com/exislow/tidal-dl-ng/issues/239

**Comment by Huber1** [comment]
Ah ok, thanks. then i'll just wait 'till it's on pypi.
regarding cover i meant the album cover, not the track one, like it is done when downloading a complete album.
So is it currently possible to get the album cover when downloading a single track?

And Thanks for your work on this package!

**Comment by exislow** [comment]
> So is it currently possible to get the album cover when downloading a single track?

As you can see in #125 we decided on, that an album can be downloaded to a `.jpg` file, only if an album is downloaded. If you are downloading a single track, you can embed the cover into the audio file. I suggest that you write yourself a post processing script, which extracts the embedded album covers as you like it.

**Comment by Huber1** [comment]
Will do,
thanks for the quick reply!
