### ISSUE TITLE
[Help] Atmos

### ISSUE THREAD

**Issue by yerbas07** [exislow/tidal-dl-ng#261]
### I need Help.

How can I download Dolby Atmos files, like I was able to download MQA files before?

### What operating system are you seeing the problem on?

None

### Your settings

```json
How can I download Dolby Atmos files, like I was able to download MQA files before?
```

**Comment by ryoko7** [comment]
Duplicate of #106. There's currently no known ability for detecting+downloading Atmos, AFAIK

**Comment by yerbas07** [comment]
Is there any plan to implement the ability to download the ATMOS format in the application? **Atmos has a future.**
