### ISSUE TITLE
[Help] issue when running the "TIDAL-Downloader-NG.exe"

### ISSUE THREAD

**Issue by flamespeedy** [exislow/tidal-dl-ng#263]
### I need Help.

getting this issue when clicking the "TIDAL-Downloader-NG.exe"
it was working before, now it doesn't work at all.

Traceback (most recent call last):
  File "tidal_dl_ng\gui.py", line 1104, in <module>
  File "tidal_dl_ng\gui.py", line 1095, in gui_activate
  File "tidal_dl_ng\gui.py", line 117, in __init__
  File "tidal_dl_ng\gui.py", line 129, in init_tidal
  File "tidal_dl_ng\config.py", line 124, in login_token
  File "tidalapi\session.py", line 448, in load_oauth_session
  File "tidalapi\request.py", line 148, in request
  File "tidalapi\request.py", line 117, in basic_request
  File "tidalapi\session.py", line 791, in token_refresh
tidalapi.exceptions.AuthenticationError: Authentication failed

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{
    "skip_existing": true,
    "lyrics_embed": false,
    "lyrics_file": false,
    "video_download": true,
    "download_delay": true,
    "download_base_path": "C:\\Users\\Connor\\Downloads",
    "quality_audio": "HI_RES_LOSSLESS",
    "quality_video": "1080",
    "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{track_volume_num_optional}{album_track_num}. {artist_name} - {track_title}",
    "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}",
    "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}",
    "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}",
    "format_video": "Videos/{artist_name} - {track_title}{track_explicit}",
    "video_convert_mp4": true,
    "path_binary_ffmpeg": "C:\\Users\\Connor\\Desktop\\Ffmpeg screenshots\\ffmpeg.exe",
    "metadata_cover_dimension": "1280",
    "metadata_cover_embed": true,
    "cover_album_file": true,
    "extract_flac": true,
    "downloads_simultaneous_per_track_max": 20,
    "download_delay_sec_min": 3.0,
    "download_delay_sec_max": 5.0
}
```

**Comment by exislow** [comment]
Duplicate #185
