### ISSUE TITLE
[Bug] Release 0.21.2 is flagged by microsoft defender as containing a trojan.

### ISSUE THREAD

**Issue by maoravni** [exislow/tidal-dl-ng#264]
### What happened?

![image](https://github.com/user-attachments/assets/82b4cfb8-9d3c-440a-bda7-8d1daec0e8d8)

### Version App

0.21.2

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
NA
```

**Comment by exislow** [comment]
Duplicate #231

**Comment by yo1nkers** [comment]
> Duplicate #231

Not particularly, Windows Defender is a core system in Windows. Works a lot differently from Bitdefender, as it will keep falsely flagging and auto-removing the .exe regardless of whether you flag it as safe
