### ISSUE TITLE
[Feature] Configure resolution of artwork and addition of PNG artwork option 

### ISSUE THREAD

**Issue by GiulioCDI** [exislow/tidal-dl-ng#266]
### Current Situation

Presently we are unable to select the quality of the embedded artwork in the music file. Additionally JPEG is the only artwork file format available.

### Suggestion / Feature Request

It would be nice to be able to select both the desired resolution of the artwork and the file format (PNG or JPEG). Assuming Tidal has support for different artwork resolutions, a drop-down list of all available options would be ideal. Additionally, this would also apply to the cover.jpeg that is downloaded when downloading an album.

**Comment by exislow** [comment]
I assume you have not checked the options. Just get more familiar with them. Artwork is passed as it comes from TIDAL. No modification are intended.

**Comment by GiulioCDI** [comment]
Apologies for the error, their is indeed a drop-down menu with various cover resolutions available. I assume Tidal does not host larger than 1280x1280 artworks. This request can safely be ignored sorry for the inconvenience.
