### ISSUE TITLE
[Help] PermissionError: [WinError 5] Access is denied on ffmpeg

### ISSUE THREAD

**Issue by Xebml1** [exislow/tidal-dl-ng#272]
### I need Help.

Hello everyone, 

I'm trying to download an album but i'm getting  PermissionError: [WinError 5] Access is denied after some console logs about ffmpeg, I already give permissions to the bin folder of ffmpeg and the download folder. 

Thanks in advance 
![Screenshot 2024-12-08 163052](https://github.com/user-attachments/assets/e19b2d06-8328-44d7-bda1-ca9ea42b4627)

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing":true,"lyrics_embed":false,"lyrics_file":true,"video_download":true,"download_delay":true,"download_base_path":"C:/TidalMusic","quality_audio":"HI_RES_LOSSLESS","quality_video":"1080","format_album":"Albums/{album_artist} - {album_title}{album_explicit}/{track_volume_num_optional}{album_track_num}. {artist_name} - {track_title}{album_explicit}","format_playlist":"Playlists/{playlist_name}/{artist_name} - {track_title}","format_mix":"Mix/{mix_name}/{artist_name} - {track_title}","format_track":"Tracks/{artist_name} - {track_title}{track_explicit}","format_video":"Videos/{artist_name} - {track_title}{track_explicit}","video_convert_mp4":true,"path_binary_ffmpeg":"C:/Windows/ffmpeg/bin","metadata_cover_dimension":"320","metadata_cover_embed":true,"cover_album_file":true,"extract_flac":true,"downloads_simultaneous_per_track_max":20,"download_delay_sec_min":3.0,"download_delay_sec_max":5.0}
```

**Comment by Xebml1** [comment]
Edit: This is only happening with some albums, with this one for example: https://tidal.com/browse/album/401317276, GNX by Kendrick Lamar, but I can download and convert correctly this one: https://tidal.com/browse/album/72694579 which is the album DAMN by the same artist.

**Comment by exislow** [comment]
Read help of option `path_binary_ffmpeg` and follow the instructions correctly (you need to set the path to the binary file).
