### ISSUE TITLE
[Feature] prefix 0 for single digit track numbers for {album_track_num}

### ISSUE THREAD

**Issue by cavalrymargarine0x1** [exislow/tidal-dl-ng#275]
### Current Situation

Apologies if this already possible, I've searched the existing issues alongside the [documentation](https://tidalapi.netlify.app/) for [tidalapi](https://github.com/tamland/python-tidal) you [referenced](https://github.com/exislow/tidal-dl-ng/issues/245#issuecomment-2492304651), but I can't find any info regarding the subject of my ticket.

Right now it doesn't seem possible to prefix a 0 to single digit track numbers for {album_track_num}. The desired result would be to have tracks numbered like this: 01, 02, 03, 04.... instead of the current 1, 2, 3, 4....

### Suggestion / Feature Request

A setting to have single digit track numbers prefixed by a 0 when using {album_track_num}

The desired result would be to have tracks numbered like this: 01, 02, 03, 04.... instead of the current 1, 2, 3, 4....

Thanks!

**Comment by exislow** [comment]
Duplicate #142
