### ISSUE TITLE
[Help]  Something went wrong while downloading  File is corrupt!

### ISSUE THREAD

**Issue by Samigulla** [exislow/tidal-dl-ng#279]
### I need Help.

I can't download some tracks in FLAC 24-bit. Some tracks from one album are downloaded, but others from the same album are not downloaded, the "extract FLAC" function is enabled, and it says "Something went wrong while loading. The file is corrupted!"

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
"quality_audio": "HI_RES_LOSSLESS",
    "quality_video": "1080",
    "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{track_volume_num_optional}{album_track_num}. {artist_name} - {track_title}{album_explicit}",
    "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}",
    "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}",
    "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}",
    "format_video": "Videos/{artist_name} - {track_title}{track_explicit}",
    "video_convert_mp4": false,
    "path_binary_ffmpeg": "C:\\FFmpeg\\bin\\ffmpeg.exe",
    "metadata_cover_dimension": "1280",
    "metadata_cover_embed": true,
    "cover_album_file": true,
    "extract_flac": true,
    "downloads_simultaneous_per_track_max": 20,
    "download_delay_sec_min": 3.0,
    "download_delay_sec_max": 5.0

```

**Comment by exislow** [comment]
Cannot help you if you do not provide information how to re-produce this issue.

**Comment by Samigulla** [comment]
> Мы не сможем вам помочь, если вы не предоставите информацию о том, как воспроизвести эту проблему.

After the update, I started downloading 24bit flac, but only if I download one track at a time. If I download the entire album at once, it says "Something went wrong while downloading File is corrupt!"

**Comment by Samigulla** [comment]
> Cannot help you if you do not provide information how to re-produce this issue.

After the update v0.22.0 , I started downloading 24bit flac, but only if I download one track at a time. If I download the entire album at once, it says "Something went wrong while downloading File is corrupt!"

**Comment by exislow** [comment]
To be honest: If you cannot provide a full config dump, logs, very specific description on how to re-produce this, proofs in form of screenshots etc. I simply cannot help you and need to close this issue. Up to you, buddy.
