### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NikolaZhechev** [exislow/tidal-dl-ng#28]
I copy the url but it still won't let me log in?[
![Екранна снимка 2024-02-02 152325](https://github.com/exislow/tidal-dl-ng/assets/42648693/7586e898-985d-48e7-8788-998b7e937995)
](url)

**Comment by exislow** [comment]
This is not enough information, man. Please be more precise.

**Comment by NikolaZhechev** [comment]
[
![ssd](https://github.com/exislow/tidal-dl-ng/assets/42648693/b2910064-1f4e-40c1-abf6-c11f82944c40)
](url)

**Comment by NikolaZhechev** [comment]
![Екранна снимка 2024-02-02 154415](https://github.com/exislow/tidal-dl-ng/assets/42648693/e167a0a7-82d3-4b7a-9e79-b74dd6f15415)

**Comment by exislow** [comment]
Try to click on the url rather then copy. And try to answer within one comment, thanks.

**Comment by NikolaZhechev** [comment]
> Опитайте да щракнете върху URL адреса, вместо да копирате. И се опитайте да отговорите в рамките на един коментар, благодаря.

okay I'm sorry.
and how to get to the earl address?

**Comment by exislow** [comment]
As I said, click on it.
