### ISSUE TITLE
[Bug] The new version does not work.

### ISSUE THREAD

**Issue by vad62** [exislow/tidal-dl-ng#284]
### What happened?

Updated version 0.15.6, which works fine on 0.23.0. The new version does not start, I return the old version 0.15.6 and everything works again. What is the problem?

### Version App

v0.23.0 macOS 11.7.10 MacBook Pro (Retina, 13-inch, Mid 2014)

### What operating system are you seeing the problem on?

macOS

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": false, "download_delay": false, "download_base_path": "~/download", "quality_audio": "HI_RES_LOSSLESS", "quality_video": "1080", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}[{album_year}]/{album_track_num} - {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "/Users/vadimlvov/download/ffmpeg", "metadata_cover_dimension": "1280", "extract_flac": true, "downgrade_on_hi_res": false}
```

**Comment by exislow** [comment]
Your macOS is too old. You need to update it to at least macOS 13 or compile it yourself. This is because GitHub does not offer any macOS 12 runner anymore for building apps, which support older macOS versions. 

To compile it yourself simply run `make gui-macos-dmg`

**Comment by vad62** [comment]
> To compile it yourself simply run make gui-macos-dmg

Thank you. I have a request for you, I have never done this and I don’t know how. Could you explain (teach me) how to do this.
