### ISSUE TITLE
[Help]  - why all the different emails being sent out 

### ISSUE THREAD

**Issue by sujay1599** [exislow/tidal-dl-ng#288]
### I need Help.

![image](https://github.com/user-attachments/assets/1e0e7a6c-28bb-4137-807c-cd37752fc8a2)

![image](https://github.com/user-attachments/assets/e76bab05-a8e1-4401-a2cb-ba8ad5749cbc)

hhhmmm??

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
just ran exe
```

**Comment by HanSolo71** [comment]
There are no emails being sent out. If you open the file you can easily see there is no email encoding present. It appears be coordinate data.

**Comment by exislow** [comment]
@sujay1599: Try harder next time to describe what ever you intend to ask. This way nobody can help you.

**Comment by sujay1599** [comment]
Yeh it was coordinate maps; but this time nord 32 did populate a warning while previously it did not.
