### ISSUE TITLE
[Bug] The exe file is found in 29 antiviruses out of  Virus Total

### ISSUE THREAD

**Issue by Damians0** [exislow/tidal-dl-ng#290]
### What happened?

I scanned the tidal downloader exe file on virus total and it shows positive on 29 antiviruses.

![Screenshot 2024-12-22 at 10-06-20 VirusTotal - File - d1e143dc5dc8ca692902015f2ede17b8418124f71298c2dc1a76e31b541f4802](https://github.com/user-attachments/assets/12d079c1-04ee-45ff-b63c-f38ff4fa131a)

### Version App

v0.23.0

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
%HOMEPATH%\.config\tidal_dl_ng\settings.json
```

**Comment by exislow** [comment]
Duplicate #231
