### ISSUE TITLE
[Bug] Downloading mp4 files with option set to False

### ISSUE THREAD

**Issue by ryba3310** [exislow/tidal-dl-ng#291]
### What happened?

With configure option 'video_download = False' tidal-dl-ng still downloads mp4 files instead of audio format only. Not sure if in the air conversion is possible but its ffmpg it does everything.

### Version App

0.23.0

### What operating system are you seeing the problem on?

```
cat /etc/*release
ID=ec2
VERSION="20240717-1811"
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Your settings

```json
{
    "skip_existing": true,
    "lyrics_embed": false,
    "lyrics_file": false,
    "video_download": false,
    "download_delay": true,
    "download_base_path": "/home/admin/Music/tidal/",
    "quality_audio": "HIGH",
    "quality_video": "480",
    "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{track_volume_num_optional}{album_track_num}. {artist_name} - {track_title}{album_explicit}",
    "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}",
    "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}",
    "format_track": "Tracks/{artist_name}. {track_title}{track_explicit}",
    "format_video": "Videos/{artist_name} - {track_title}{track_explicit}",
    "video_convert_mp4": false,
    "path_binary_ffmpeg": "",
    "metadata_cover_dimension": "320",
    "metadata_cover_embed": true,
    "cover_album_file": true,
    "extract_flac": true,
    "downloads_simultaneous_per_track_max": 20,
    "download_delay_sec_min": 3.0,
    "download_delay_sec_max": 5.0,
    "album_track_num_pad_min": 1,
    "downloads_concurrent_max": 3,
    "symlink_to_track": false,
    "playlist_create": false
}
```

**Comment by exislow** [comment]
Cannot help you if you do not provide exact directions how to re-produce this. Also proofs to your statement are missing.

**Comment by ryba3310** [comment]
Hope this clarifies a bit.
![tdn_issue](https://github.com/user-attachments/assets/075ea302-5f9a-4291-a2c4-014cd0c893f1)

**Comment by exislow** [comment]
Your posted config does not make any sense in comparison with your screenshot. Also your playlist does not contain a single video. What is your point?

**Comment by ryba3310** [comment]
Didn't realize there is no video, then it's probably just a file naming issue and Navidrome doesn't take into account .mp4 extension. Sorry for wasting your time.

**Comment by exislow** [comment]
If it is not a video, it is related to this: https://github.com/tamland/python-tidal/issues/309

-> It is a naming issue.

It is fixed in my master branch already, but I can only release it, after `tidalapi` has made a new release with my fix.
