### ISSUE TITLE
[Help] [Bug] False positive? Trojan sushil!rfn

### ISSUE THREAD

**Issue by mversion** [exislow/tidal-dl-ng#292]
### I need Help.

Trying to download the latest windows-x64 release, Windows Defender gives me the above threat warning. I'm assuming it's a false positive?

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
zip file issue
```

**Comment by dreamcoders-pl** [comment]
Not only the Defender, but also Firefox warns when trying to download this file.

**Comment by exislow** [comment]
Duplicate #231
