### ISSUE TITLE
[Help] Downloaded tracks are saved in m4a files instead of flac..

### ISSUE THREAD

**Issue by Damians0** [exislow/tidal-dl-ng#294]
### I need Help.

Downloaded tracks are saved in m4a files instead of flac..
When I click on a track to select it and then click on the download button the track is saved in m4a format.
I want the track to be saved in flac format
Do I need to install FFmpeg?

App Version: v0.23.0

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"token_type": "Bearer", "access_token": "eyJraWQiOiJ2OU1GbFhqWSIsImFsZyI6IkVTMjU2In0.eyJ0eXBlIjoibzJfYWNjZXNzIiwidWlkIjoyMDE5MDQ2OTUsInNjb3BlIjoid191c3Igd19zdWIgcl91c3IiLCJnVmVyIjowLCJzVmVyIjowLCJjaWQiOjgwMTcsImN1ayI6IjE2MjVkNTk3NTA4OTc5NGIiLCJleHAiOjE3MzUwMzYzMjEsInNpZCI6IjhkNmVjMDdhLTA2ODYtNDZhMi04NmNkLTM1ODRlNjAzZGM5YSIsImlzcyI6Imh0dHBzOi8vYXV0aC50aWRhbC5jb20vdjEifQ.94cVLaTSqjugKK_7m0-p9JU1BXbML6Snduxah7UoZ7c2neLsaqVOJ65Ee6G8IzHE_pjZ_qXAo6W_cgUjFaXklQ", "refresh_token": "eyJraWQiOiJoUzFKYTdVMCIsImFsZyI6IkVTNTEyIn0.eyJ0eXBlIjoibzJfcmVmcmVzaCIsInVpZCI6MjAxOTA0Njk1LCJzY29wZSI6IndfdXNyIHdfc3ViIHJfdXNyIiwiY2lkIjo4MDE3LCJzVmVyIjowLCJnVmVyIjowLCJjdWsiOiIxNjI1ZDU5NzUwODk3OTRiIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLnRpZGFsLmNvbS92MSJ9.AINE5l9m3uWS6hSJ_B-vTQKbdGMqqMekqapPLWDdHpRGLum37eECBO6CoO4nkAHqJmNMJDk7h8Am9Vk2bGiulvlLABNrrYux3u1mDLTPpLJ11PJutBAyw5evUXFB8XnZ89-jawNfZ0dinlWa0nD1fRCP_x60TFeNNq-HL2LJD9Ai1pUU", "expiry_time": 1735032714.756323}
```

**Comment by exislow** [comment]
You have posted your personal access token. Thus I have deleted this issue. Buddy, you really should put more effort in issues. If you keep copy & pasting your "quick work" I will keep closing it. Just follow the directions in the issue template. Cannot be so hard, huh?
