### ISSUE TITLE
[Help] Downloaded tracks are saved in m4a files instead of flac

### ISSUE THREAD

**Issue by Damians0** [exislow/tidal-dl-ng#295]
### I need Help.

Downloaded tracks are saved in m4a files instead of flac..
When I click on a track to select it and then click on the download button the track is saved in m4a format.
I want the track to be saved in flac format
Do I need to install FFmpeg?

App Version: v0.23.0

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "E:\\Musica\\Tidal Download", "quality_audio": "LOSSLESS", "quality_video": "480", "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{track_title}{track_explicit}", "format_video": "Videos/{artist_name} - {track_title}{track_explicit}", "video_convert_mp4": false, "path_binary_ffmpeg": "", "metadata_cover_dimension": "320", "extract_flac": false, "downgrade_on_hi_res": true}
```

**Comment by Damians0** [comment]
I discovered that the tracks are saved in flac only if I choose High_lossless as the quality format, if I choose hires or hires_lossless the tracks are saved in m4a.
Is there a way to also save the tracks downloaded in hires and hires_lossless in flac?

**Comment by orbittwz** [comment]
hmm, you suppose to use FFMPEG for hires FLAC encoding.
in the options of the application check the extract FLAC option and install FFMPEG beforehand.
![image](https://github.com/user-attachments/assets/d926480d-ddf7-47ff-8539-f7e4e05d2898)

**Comment by Damians0** [comment]
Thanks it worked. I wonder if it is really worth saving music in 24 bit 96 Khz flac instead of 16 bit 44 Khz.
I wonder if there really is an advantage in terms of quality or is it just a placebo effect.

**Comment by orbittwz** [comment]
I noticed some differences in the lower notes, you can hear sounds you can't on 16bit.
in any case, if solved, you can close the issue.
cheers!
