### ISSUE TITLE
Tidal-dl-ng some bugs

### ISSUE THREAD

**Issue by grizzlio** [exislow/tidal-dl-ng#3]
I have tested the new ui version, my operating system is windows 10.

and I found these bugs:

- initially when i put the parameters in hi_res_lossles the program closes suddenly. i have started it again and i have put the value in hi_res and everything went correctly. Although it is not 24B, that is another matter.

- the album comes out without the album name, instead it says {title}.

- the file options button doesn't work, I haven't got it to do anything.

I will continue to report any errors I find. thanks for your work.

**Comment by exislow** [comment]
Thank you very much for your feedback. I really appreciate it and will try to fix them in January. I am happy about any other bugs you can report.

**Comment by exislow** [comment]
>     * initially when i put the parameters in hi_res_lossles the program closes suddenly. i have started it again and i have put the value in hi_res and everything went correctly. Although it is not 24B, that is another matter.

I will look into it. Main issue for this is #9.

>     * the album comes out without the album name, instead it says {title}.

This was fixed with #13 and will be released as a new version soon.

>     * the file options button doesn't work, I haven't got it to do anything.

This is correct, since this is not implemented, yet.
