### ISSUE TITLE
Cant seem to get it running

### ISSUE THREAD

**Issue by wjbeckett** [exislow/tidal-dl-ng#3]
Installing tidal-dl-ng via pip, seems to succeed however when trying to run `tidal-dl-ng` I get a command not found error.

**Comment by exislow** [comment]
I can confirm that. Will try to fix it ASAP.

**Comment by wjbeckett** [comment]
Thanks for that. 
Was trying to get a dev environment up and running to help with my second request #4 , but was getting caught out by this.

**Comment by exislow** [comment]
For now simply clone this repository and do this to get it running:

```bash
poetry install
python3 /tidal_dl_ng/cli.py
```

**Comment by exislow** [comment]
Issue fixed with this release: https://github.com/exislow/tidal-dl-ng/releases/tag/v0.4.5
