### ISSUE TITLE
what is the problem?

### ISSUE THREAD

**Issue by edin8803** [exislow/tidal-dl-ng#30]
https://github.com/exislow/tidal-dl-ng/assets/158776584/1463a6a0-d23f-451e-bc02-079f7710b699

why won't it let me sign in with my details?

**Comment by exislow** [comment]
The video does not show the first part, how you click on the link in the red box etc. From this point of view I cannot help. Try to click on the blue link, login and the correctly copy the "oops" page's URL from the browser,
