### ISSUE TITLE
Question: why Hi-Res-Lossless quality is only available for a limited time

### ISSUE THREAD

**Issue by rockstar2020** [exislow/tidal-dl-ng#31]
Hi @exislow ,
I have a question.
When I login and authenticate via PKCE method I'm able to download at HI_RES_LOSSLESS quality with no issues.
But after several hours (<24hrs) the best quality I can get with exatcly the same settings is 44/16.
When I delete the token.json and re-login, I'm again able to download at MAX quality.
Why is this happening?
Is there any workaround?
Thanks in advance for your help.

Cheers

**Comment by exislow** [comment]
That sounds interesting. Haven't noticed it so far. I will do some investigation and come back to you.

**Comment by exislow** [comment]
Can you please confirm, that the latest release fixes this issue?

**Comment by rockstar2020** [comment]
> Can you please confirm, that the latest release fixes this issue?

Thanks for the new release but I'm currently on business trip and not able to test it.
I can only check and provide you feedback this Friday.
Appreciate, the quick fix though!

**Comment by rockstar2020** [comment]
Hi @exislow,
I tested the new release and it fixed the issue.
Thanks a lot!
