### ISSUE TITLE
How to know what can I set in config

### ISSUE THREAD

**Issue by Xayayia** [exislow/tidal-dl-ng#36]
Noob question I guess but I dont know to what can I change quality audio in config on not gui version. It's HIGH now but what else can it be? Info is either not accessible or I dont know how to see it.

**Comment by exislow** [comment]
Get the very latest version and run: `tidal-dl-ng cfg`

**Comment by Xayayia** [comment]
well I do that and can only see how it's set up, but I don't see options. I'm running this in termux on android, maybe this matters
![Screenshot_20240206-172938_Termux](https://github.com/exislow/tidal-dl-ng/assets/130109314/a3301c23-5f24-45df-a976-02c798d22898)

**Comment by exislow** [comment]
Let's do not waist each others time and follow instructions: https://github.com/exislow/tidal-dl-ng/issues/36#issuecomment-1930234464

-> Install the latest version.

**Comment by Xayayia** [comment]
![Screenshot_20240206-173948_Termux](https://github.com/exislow/tidal-dl-ng/assets/130109314/49a2e383-ec4a-4495-a060-c4be8b638a48)
as u see it's already the latest version
