### ISSUE TITLE
[Feedback] Possibility to use direct links to albums/playlists/tracks

### ISSUE THREAD

**Issue by morgenstern09** [exislow/tidal-dl-ng#37]
Hello, thank you very much for your effort! It's nice to be able to download Hi-Res tracks!

Would it be possible in a future version to be able to use direct links to albums/playlists/tracks? Example (album): https://tidal.com/browse/album/74414448

We can get these links when we use the "Share" function in Tidal.

Edit: I'm not sure if there is a CLI version, I was referring to the GUI version. If I put the link in the search box and press Enter, it just searches on Tidal:
![image](https://github.com/exislow/tidal-dl-ng/assets/31675407/66569a91-5868-4e30-a1be-e631b7ce28cc)

Edit 2 - I also found a CLI version, which is nice. There are some more things that would be nice to have in the GUI:
- Possibility to cancel the current download
- Maybe the possibility to queue multiple downloads of tracks/albums/etc. (and having a list where we can see what's in the queue, and the possibility to cancel some of the downloads that are placed in the queue).
- Some info about all the "elements" we can use in the settings for paths/names (ex. {artist_name} ).

**Comment by exislow** [comment]
Thank you for your valuable feature requests. I have put in on the list.

**Comment by exislow** [comment]
Direct link search is implemented in `master` branch.

**Comment by exislow** [comment]
> Direct link search is implemented in `master` branch.

Released in https://github.com/exislow/tidal-dl-ng/releases/tag/v0.8.3

**Comment by exislow** [comment]
I have created new issues for the other suggestions, see #70 and #71
