### ISSUE TITLE
[GUI]When lyrics download is enabled, if there are no lyrics with the song, the download will get stuck.

### ISSUE THREAD

**Issue by AuroraStar05** [exislow/tidal-dl-ng#38]
When lyrics download is enabled, if there are no lyrics in the song, the download will get stuck.
![image](https://github.com/exislow/tidal-dl-ng/assets/53976308/3d3d71d8-088c-4963-8094-2af5fcc83e16)
![image](https://github.com/exislow/tidal-dl-ng/assets/53976308/586376bf-f953-4647-8d28-00d4c546ece2)

BTW,Can you add an option for multithread counts? sometimes I'd like to tweak them manually

**Comment by exislow** [comment]
Thank you for reporting this issue. It is fixed and will be released soon.

**Comment by exislow** [comment]
Please test it: https://github.com/exislow/tidal-dl-ng/releases/tag/v0.8.2

**Comment by AuroraStar05** [comment]
> Please test it: https://github.com/exislow/tidal-dl-ng/releases/tag/v0.8.2

I tested the new release and it fixed the issue.
Thanks a lot!

**Comment by AuroraStar05** [comment]
> Please test it: https://github.com/exislow/tidal-dl-ng/releases/tag/v0.8.2

Seems like it's still reporting an error, But good news, it won't get stuck anymore.
![image](https://github.com/exislow/tidal-dl-ng/assets/53976308/3a03276c-a2c0-44cf-a79e-03c29c35c689)

**Comment by exislow** [comment]
This is fine. Not every track has lyrics. Thank you for testing.
