### ISSUE TITLE
Add the ability to grab Tidal Mixes

### ISSUE THREAD

**Issue by wjbeckett** [exislow/tidal-dl-ng#4]
It seems that Mixes and Playlists are treated differently.
Playlists contain an ID, whereas Mixes seem to not have an ID assigned to them due to their dynamic nature.

It would be good if Mixes could be included, perhaps just omitting the requirement of the ID if "mix" is in the URL.

**Comment by exislow** [comment]
I will have a look into it and try to figure out how to implement this feature. You. can use the following workaround for now: Save the Mix as a Playlist and simply download the Playlist.

**Comment by wjbeckett** [comment]
> I will have a look into it and try to figure out how to implement this feature. You. can use the following workaround for now: Save the Mix as a Playlist and simply download the Playlist.

Yeah I understand the workaround, however it's not really helpful when I want it to be Dynamic.

**Comment by exislow** [comment]
Btw... I am little confused right now. The app already supports the dynamic Mixes. Are speaking about any different mixes than that?

**Comment by wjbeckett** [comment]
I haven't tried the gui yet.
It's still erroring for me with a Typer error at the moment.

Can you try to download your Daily Discovery Mix from Tidal? This doesn't work for me and throws a tuple error.

**Comment by exislow** [comment]
I have fixed it with this release: https://github.com/exislow/tidal-dl-ng/releases/tag/v0.4.5
