### ISSUE TITLE
M4A

### ISSUE THREAD

**Issue by vad62** [exislow/tidal-dl-ng#43]
The m4a file format is not recognized by the ROON program and many digital transports/streamers. We have to convert it to the FLAC format. Make the save in the default FLAC format. What is not clear here. Rather, it is strange why it is stored in m4a, which has nothing to do with Tidal and HD FLAC.

**Comment by exislow** [comment]
Duplicate #42 

Sorry, but you really have to read and understand this https://github.com/exislow/tidal-dl-ng/issues/22#issuecomment-1923492562
