### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by cjonesdev** [exislow/tidal-dl-ng#48]
I was downloading from an old playlist, when it ran into a song that has been removed from Tidal, but is still in the playlist itself. It hits this 401 error and stops everything. I think the appropriate action would be to say that the track isn't available and move on to the next song.

Response was <Response [401]>
Response json was {'status': 401, 'subStatus': 4005, 'userMessage': 'Asset is not ready for playback'}

**Comment by exislow** [comment]
Thanks for this bug report. I have fixed it and it will be released soon.

**Comment by exislow** [comment]
Check out the new release https://github.com/exislow/tidal-dl-ng/releases/tag/v0.9.0
