### ISSUE TITLE
Windows client download paths

### ISSUE THREAD

**Issue by okinokosan** [exislow/tidal-dl-ng#49]
At the moment it seems unable to change download path for windows client (for tracks)- you can write all you want in download path it stays  default.

Regarding video download - so far cant find downloaded files at all, although download process seems to have place. Windows searching gave up on finding these files :)

**Comment by okinokosan** [comment]
Tracks download path seems to change - but after client relaunch. Still trying to find videos :)

**Comment by exislow** [comment]
The settings only have been applied after a relaunch, indeed. This is fixed now and will be available with the next release. 

Can you please provide the video (URL) you try to download, any log output, your settings (`HOME/.config/tidal_dl_ng/settings.json`), the version of this app you are using and your OS? I would like to reproduce your bug.

**Comment by exislow** [comment]
Released in https://github.com/exislow/tidal-dl-ng/releases/tag/v0.8.3

**Comment by okinokosan** [comment]
Sorry for long answer, was away for couple months. Since v0.8.3 everything is working. Convertion to .mp4 must be OFF (unchecked) for video to download, but otherwise everything is ok. Many thanks for your work.

**Comment by exislow** [comment]
Cannot confirm this. Maybe `ffmpeg path` is not set in your case.
