### ISSUE TITLE
[Bug] album artist tag messed up and download speed the same no matter the quality

### ISSUE THREAD

**Issue by Xayayia** [exislow/tidal-dl-ng#51]
### What happened?

Album artist tag has track name in it example 1st song "artist1 - track1name", 2nd song "artist1 - track2name" instead of just artist name across every album track making every track a new album (in musicbee for example) and even when im downloading songs in lowest quality (2-3MB file) it takes as long as downloading highest but im not sure if it depends on u or tidal

### Version

0.8.2

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": false, "download_base_path": "C:\\Users\\Admin\\Music", "quality_audio": "LOW", "quality_video": 360, "format_album": "Albums/{artist_name} - {album_title}/{track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}", "format_video": "Videos/{artist_name} - {track_title}", "video_convert_mp4": true, "metadata_cover_dimension": "1280x1280"}
```

**Comment by exislow** [comment]
I do not really understand what your issue is. Can you tell me what are you exactly doing and what type of error occurs? Please state what exactly happens and what you like to have instead?

I cannot influence the download speed. This correlates with your bandwidth and TIDAL itself.

**Comment by Xayayia** [comment]
![Screenshot_2](https://github.com/exislow/tidal-dl-ng/assets/130109314/bb853de2-b4a3-4516-a384-0d76ffb070dd)
look at album artist tag, it has track name in it for some reason, I would like it to not have the track name by default so it doesnt need to be changed for every album downloaded because as u see on left 2 tracks from same album are shown as separate. And u can too see the track count is always "track number of 1" so this tag needs manual correction too. So I would like u to make album artist tag be an actual album artist as shown on tidal and track count to be correct. There's no errors, just QOL change I suppose to make tags correct. All the songs are downloaded as an album, not seperately or something.

**Comment by exislow** [comment]
Thanks for your explanation. `track.album.artists.role` will now be checked, if it contains `Role.main`. All the artists with `Role.main` will be added to the album artist tag.

**Comment by exislow** [comment]
Check out the new release https://github.com/exislow/tidal-dl-ng/releases/tag/v0.9.0
