### ISSUE TITLE
Ability to use custom API Instance

### ISSUE THREAD

**Issue by sachinsenal0x64** [exislow/tidal-dl-ng#52]
### Current Situation

Problem : Tidal only available for few countries and some people can't buy (Geo Restrict / Payment Issues /  etc.)

### Suggestion / Feature Request

Note : If you don't have any interest, feel free to leave, no problem.

If you can add this API (like external adapter) it will be great, and it's totally free and open source.

Solution : https://github.com/sachinsenal0x64/hifi-tui?tab=readme-ov-file#-api-documentation

Goal : Free Access Without Any Subscription and We DO NOT encourage piracy

**Comment by sachinsenal0x64** [comment]
> I do not really understand what your project is about. Your website says, the access to TIDALs library is for free. But in fact it is not. Somebody needs to pay for a subscription. Who is paying for this?

Currently, I'm paying :)

![image](https://github.com/exislow/tidal-dl-ng/assets/127573781/3404e69a-eb6e-4476-b3f5-abc6e1f1922e)

**Comment by exislow** [comment]
If you take a closer look at this project, you will notice that it is relying on https://github.com/tamland/python-tidal

I think `python-tidal` would be the right point to implement an optional adapter. You could try to raise an issue there.
