### ISSUE TITLE
[Bug] Wrong track name for remixes, missing the track version information

### ISSUE THREAD

**Issue by CyberDev01** [exislow/tidal-dl-ng#57]
### What happened?

I found a small problem which is related to the track name (and the corresponding filename):
The bug occured e.g. for the following compilation: https://listen.tidal.com/album/199830585

Specifically the 4th track has the title "Wir werden sehen (Paul Kalkbrenner Remix 2020 edit)".
When analyzing the file the track-name consists only of the title but not the remix name (see image below).

Wrong track / file - name:
![Bildschirmfoto vom 2024-03-16 13-42-22](https://github.com/exislow/tidal-dl-ng/assets/75259133/ec00b9c5-4745-49bd-94f3-45cf16fa1120)

It would be nice if the information about remixes and other data of this kind is included in the tags.
I think the full name of the track including the version can be received by `track.full_name`.

Thank you for your work!

### Version

v0.8.3

### What operating system are you seeing the problem on?

Linux

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "/home/eric/Musik", "quality_audio": "HI_RES_LOSSLESS", "quality_video": 1080, "format_album": "{artist_name}/{album_title}/{track_num} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "{artist_name}/{track_title}/{track_num} - {track_title}", "format_video": "Videos/{artist_name}/{track_title}", "video_convert_mp4": true, "metadata_cover_dimension": "1280x1280"}
```

**Comment by exislow** [comment]
Thank you very much for this bug report and your analysis. I have fixed it with this commit https://github.com/exislow/tidal-dl-ng/commit/5c5aac11f1903805c8dc95c8eaffa9b8d9ca4c8a

**Comment by exislow** [comment]
Check out the new release https://github.com/exislow/tidal-dl-ng/releases/tag/v0.9.0
