### ISSUE TITLE
[Feature] Show the audio-resolution of an album in the search tree; Upgrade to tidalapi version 0.7.6

### ISSUE THREAD

**Issue by CyberDev01** [exislow/tidal-dl-ng#58]
### Current Situation

Currently there is no information about the audio resolution of an album or track in the result tree.
That's why we have to look in the original Tidal App or Web Player which quality the album has.

I would need the quality to make sure it's the correct album and if the album has a higher quality than the album I already have. 

### Suggestion / Feature Request

This could be done by upgrading to tidalapi version 0.7.5 and the use of the `get_audio_resolution` - method which is part of the album class. 
As this results in a much higher traffic load this should only be executed on the album and not the individual tracks.
For the individual tracks there is the `audio_quality` option, but I don't know how big the impact of this method is if it's executed on every track.

**Comment by exislow** [comment]
Thank you for sharing your idea. Currently `tidalapi == 0.7.5` has some breaking changes, which needs to be handled carefully. Thus, the version upgrade will take some time.

**Comment by crankedguy** [comment]
I think the breaking changes you are referring to were reverted in the actual version 0.7.6, so it might be easier for you to upgrade now. free way for audio resolution etc...

https://github.com/tamland/python-tidal/releases/tag/v0.7.6

**Comment by exislow** [comment]
I have tried to use `get_audio_resolution` but it is VERY resource intensive. The API call overhead makes the app very slow on querying results. Thus, I have implemented a feature which simply show the general audio quality, in terms of this https://github.com/tamland/python-tidal/blob/6fb5289b698fe40974abf19c0f283b787526ad97/tidalapi/media.py#L56-L61
