### ISSUE TITLE
[Bug] Files are kinda corrupted when downloaded at quality high_lossless or higher

### ISSUE THREAD

**Issue by Xayayia** [exislow/tidal-dl-ng#59]
### What happened?

Example https://tidal.com/browse/track/345695655. When I'm trying to import the downloaded files to MusicBee library it shows errors that file is corrupted. The song plays normally, but all tags are empty and stuff like bitrate or sample rate is unknown. Checked it in (windows 11) Media Player and there are tags shown and editable but the bit rate is still unknown/nothing so there has to be something wrong with the file. I checked if embeded lyrics matter, they dont.

### Version

0.8.3

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": false, "lyrics_embed": false, "lyrics_file": false, "video_download": false, "download_delay": false, "download_base_path": "C:\\Users\\PingwinekX\\Music", "quality_audio": "HI_RES_LOSSLESS", "quality_video": 360, "format_album": "Albums/{artist_name} - {album_title}/{track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}", "format_video": "Videos/{artist_name} - {track_title}", "video_convert_mp4": true, "metadata_cover_dimension": "320x320"}
```

**Comment by exislow** [comment]
This app simply writes the received data (audio) stream into a file without modifying it. What does, e.g. VLC tells you? VLC shows me a correct bitrat etc. Try also to paste the output of `mediainfo` (google the bianry) here.

I would also suggest to raise this issue to MusicBee, since it's there system which has maybe a broken analysis tool?

**Comment by Xayayia** [comment]
Ok so I did post the problem on musicbee forum and yes, it was something wrong with musicbee. Bcuz of this 0 bitrate i thought its the file, sorry. Idk if u will delete this issue but heres the post if not https://getmusicbee.com/forum/index.php?topic=40900.0 .
