### ISSUE TITLE
[Feature]  IMPORTANT: Consider changing download type from stream to direct url for Tracks

### ISSUE THREAD

**Issue by CyberDev01** [exislow/tidal-dl-ng#60]
### Current Situation

Currently the media is downlaoded as a stream via the `get_stream`-method.

The problem is that this should only be used for streaming a real song and not downloading it.
As a consequence, because of the sometimes slow download / stream speed, the download lasts longer than 30 seconds which indicates a stream in Tidal. 

Thereby not only the statistics of the personal account will be modified, 
but this also affects the amount of "streams" / "clicks" of a track which shouldn't be influenced (because artists are paid depending on the amount of streams they have and it's explicitly forbidden regarding the Usage guidelines).
In addition from the perspective of Tidal is looks like you randomly skip tracks and "hear" them a random time which could look a bit weird and suspicious.

### Suggestion / Feature Request

If it's possible to still get the higher bit-rates and sample-rates I would suggest to switch from `get_stream` to `get_url`.

**Comment by exislow** [comment]
Thank you for this well elaborated suggestions. I have used `get_url` before. Unfortunately, it is only possible to download HI_RES_LOSSLESS files with `get_stream`. Thus, it was necessary to refactor to `get_stream`.

**Comment by CyberDev01** [comment]
Thank you for considering and checking.

Would it be possible to check (only for albums) the audio resolution and only stream the file if it's higher than 24/48?

AFAIK it should be possible do get the files by using `get_url` until 48kHz and 24bit. (Maybe it changed)

**Comment by exislow** [comment]
The nature of this is very technical and is related to the login method. Currently, if you login using PKCE (which you need for HI RES LOSSLESS) you only can use `get_stream` as far as I remember. Thus, the app need to ask you depending on the chosen quality, to login again, so it is able to use `get_url` or `get_stream`. If you have a better idea I am happy about each pull request!

**Comment by CyberDev01** [comment]
Thanks for your reply!

I didn't know you can only use `get_stream` if using PKCE, because I'm not really into the PKCE-topic.

You're right, it doesn't make sense to switch between the two options if you have to log in every time you switch.

Anyway, thank you!
