### ISSUE TITLE
[Bug] Tooltips within Preference Window are very hard to read

### ISSUE THREAD

**Issue by NoDowt** [exislow/tidal-dl-ng#61]
### What happened?

Running the .exe version on Windows 11.
When you open the preferences window, the tooltip popups when hovering over the options are very hard to read, light grey text over white background.
![image](https://github.com/exislow/tidal-dl-ng/assets/106318854/107e3b38-60bb-4cf4-91b4-fbbdcd05b996)

### Version

0.8.3

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": false, "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "./download/", "quality_audio": "HIGH", "quality_video": 1080, "format_album": "Albums/{artist_name} - {title}/{track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}", "format_video": "Videos/{artist_name} - {track_title}", "video_convert_mp4": false, "metadata_cover_dimension": "640x640"}
```

**Comment by exislow** [comment]
Fixed. Will be released soon.

**Comment by exislow** [comment]
Is released.
