### ISSUE TITLE
[Bug] Version info not displayed

### ISSUE THREAD

**Issue by NoDowt** [exislow/tidal-dl-ng#62]
### What happened?

Running the exe version on Windows 11.
File > Version page isn't showing the actual version. Instead returns 0.0.0
![image](https://github.com/exislow/tidal-dl-ng/assets/106318854/ce891ab5-008e-406b-83de-45d7863b63cd)

### Version

0.8.3

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": false, "lyrics_embed": false, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "./download/", "quality_audio": "HIGH", "quality_video": 1080, "format_album": "Albums/{artist_name} - {title}/{track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}", "format_video": "Videos/{artist_name} - {track_title}", "video_convert_mp4": false, "metadata_cover_dimension": "640x640"}
```

**Comment by exislow** [comment]
This is strange. Thank you for reporting it. I will try to fix it.

**Comment by exislow** [comment]
Is fixed and will be released soon.

**Comment by exislow** [comment]
Is released.
