### ISSUE TITLE
[Feature] Provide feedback if FFMPEG not found on path

### ISSUE THREAD

**Issue by NoDowt** [exislow/tidal-dl-ng#63]
### Current Situation

Running .exe version on Windows 11.
When downloading a video, if you have the preference 'convert to mp4' enabled, but don't have FFMPEG location in PATH environment variable, process will just hang with no feedback.

### Suggestion / Feature Request

Before downloading a video, if the 'convert to mp4' option is enabled you could check for ffmpeg being in PATH and display a message before download.
Or alternatively after downloading, rather than hanging when unable to launch ffmpeg, you could provide the feedback of ffmpeg not found & leave the video as .ts file.

**Comment by exislow** [comment]
Thank you for sharing your thoughts. I will implement a check for ffmpeg.

**Comment by exislow** [comment]
Done. Will be released soon.

**Comment by exislow** [comment]
Is released.
