### ISSUE TITLE
[Bug] File name has "{track_num}." instead of the actual track number

### ISSUE THREAD

**Issue by Xayayia** [exislow/tidal-dl-ng#64]
### What happened?

![Screenshot_3](https://github.com/exislow/tidal-dl-ng/assets/130109314/907134ff-2584-43cb-94fc-97a9d246cc66)
Picture

### Version

v0.9.0

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "exact", "lyrics_embed": true, "lyrics_file": false, "video_download": false, "download_delay": false, "download_base_path": "C:\\Users\\PingwinekX\\Music", "quality_audio": "HI_RES_LOSSLESS", "quality_video": 360, "format_album": "Albums/{artist_name} - {album_title}/{track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}", "format_video": "Videos/{artist_name} - {track_title}", "video_convert_mp4": false, "metadata_cover_dimension": "1280x1280"}
```

**Comment by exislow** [comment]
Please be more precise. I do not have time to guess stuff. If you refer to the variable: It's either `{album_track_num}`, see https://github.com/exislow/tidal-dl-ng/blob/master/tidal_dl_ng/helper/path.py#L107

I will create an overview of the available placeholder soon.

**Comment by Xayayia** [comment]
I thought its just a typo somewhere and something u will know how to fix instantly, sry. I just downloaded an album and the files are named like this, I dont know enough to say anything more

**Comment by exislow** [comment]
Go to settings and use the correct placeholder variable as described here :-) https://github.com/exislow/tidal-dl-ng/issues/64#issuecomment-2014623018
