### ISSUE TITLE
Error for Windows 11

### ISSUE THREAD

**Issue by NikolaZhechev** [exislow/tidal-dl-ng#69]
### What happened?

The app won't start for me

![Екранна снимка 2024-03-22 205539](https://github.com/exislow/tidal-dl-ng/assets/42648693/860ed2af-6f50-47c0-9176-874b08bad809)

### Version

Windows 11 Home (10.0.22631)

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
unhandled exception in script
```

### Your settings

```json
Traceback (most recent call last):
  File "tidal_dl_ng\gui.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "tidal_dl_ng\dialog.py", line 5, in <module>
ModuleNotFoundError: No module named 'helper'
```

**Comment by exislow** [comment]
Thank you for bug report. It's fixed. Try this release: https://github.com/exislow/tidal-dl-ng/releases/tag/v0.10.1
