### ISSUE TITLE
TIDAL-Downloader-NG.exe - Doesn't display multiple artists on tracks

### ISSUE THREAD

**Issue by NoDowt** [exislow/tidal-dl-ng#7]
OS: Windows 11
TIDAL-Downloader-NG.exe release 0.4.31

When searching for songs & tracks have multiple artists, only the first artist is displayed in the GUI. Can make it tricky when trying to select particular versions/remixes of a song.

**Comment by exislow** [comment]
Thanks for this report. I will fix this in January.

**Comment by exislow** [comment]
Is fixed and will be released soon.
