### ISSUE TITLE
Gui and command line not working on Windows

### ISSUE THREAD

**Issue by magicbluemonkeydog** [exislow/tidal-dl-ng#7]
When I try to run the gui with either tidal-dl-ng-gui or tidal-dl-ng gui I get:

```
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\python\scripts\tidal-dl-ng-gui.exe\__main__.py", line 4, in <module>
  File "c:\python\lib\site-packages\tidal_dl_ng\gui.py", line 256
    result_search: [dict[str, *SearchTypes]] = self.tidal.session.search(query, models=types_media, limit=999)
                    ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

When I try and download a track with this command:

`tidal-dl-ng dl https://tidal.com/browse/track/200021907`

I get:

`AttributeError: module 'os' has no attribute 'pathconf'`

**Comment by exislow** [comment]
Can you please edit your post and add the commands you have executed?

**Comment by magicbluemonkeydog** [comment]
> Can you please edit your post and add the commands you have executed?

Done.

**Comment by exislow** [comment]
Thank you! Seems to be some issues with Windows. I will take care about that. What Windows version are you using?

**Comment by magicbluemonkeydog** [comment]
Windows 11.

**Comment by exislow** [comment]
What python version do you use? `python --version` please.

**Comment by magicbluemonkeydog** [comment]
3.10.11

**Comment by exislow** [comment]
Fixed with https://github.com/exislow/tidal-dl-ng/releases/tag/v0.4.11

Please update and test. I am happy to get every bug reported you can find :-)
