### ISSUE TITLE
[Feature] Prefer BTS over MPD

### ISSUE THREAD

**Issue by exislow** [exislow/tidal-dl-ng#73]
### Current Situation

Currently all files will be handled with MPD mode. But this is only necessary for HI_RES_LOSSLESS.

### Suggestion / Feature Request

With `tidalapi >= 0.7.5` comes a method which allows to check for the available quality. Use it to distinguish, if a MPD download is really necessary.

**Comment by crankedguy** [comment]
After a bit of searching this https://github.com/exislow/tidal-dl-ng/issues/60 answered why the hell my downloads are so slow with 800Mbit of free bandwidth. Are we sure there is absolutely no way around it? As what the OP said could be look pretty bad in terms of what happens TIDAL internal then.

**Comment by exislow** [comment]
Feel free to share possible solutions or even better, some well tested pull requests!

**Comment by crankedguy** [comment]
I will let you know if I have some findings or gather knowledge about this matter. Thanks man!
