### ISSUE TITLE
Should only use delay if the file doesn't already exist

### ISSUE THREAD

**Issue by rudy-lath-vizio** [exislow/tidal-dl-ng#8]
Currently, it seems like when we download a playlist, the program will have human-like delays before it downloads a track, which is what we want. But, there is also a case where you can have 1000 tracks out 1010 total downloaded already, in which case it applies the delay to every song even if it already exists. Ideally, it should check is a file for the requested track already exists, and if it does, then skip delay and move to the next request.

cc: @exislow

**Comment by exislow** [comment]
Yes, you are right. Will fix this soon and drop you a notice.

**Comment by exislow** [comment]
Is fixed and will be released soon.
