### ISSUE TITLE
[Help] Lossless files saved as m4a rather than Flac extension/container

### ISSUE THREAD

**Issue by NoDowt** [exislow/tidal-dl-ng#81]
### I need Help.

Not sure if this is a change from your side, or maybe Tidals side... But earlier lossless files I've downloaded would have the .flac extension.
After updating to the latest version, noticed that lossless files are saved with the .m4a extension/container instead.

I'll often download both the low_320k & high_lossless options, which obviously only works if they have different extensions.

### What operating system are you seeing the problem on?

Windows

### Your settings

```json
{"skip_existing": "False", "lyrics_embed": true, "lyrics_file": false, "video_download": true, "download_delay": true, "download_base_path": "D:\\Tidal-dl-ng\\download", "quality_audio": "LOSSLESS", "quality_video": 1080, "format_album": "Albums/{album_artist} - {album_title}/{album_track_num}. {artist_name} - {track_title}", "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}", "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}", "format_track": "Tracks/{artist_name} - {track_title}", "format_video": "Videos/{artist_name} - {track_title}", "video_convert_mp4": true, "path_binary_ffmpeg": "D:\\ffmpeg\\ffmpeg.exe", "metadata_cover_dimension": 640}
```

**Comment by Jay-BRF** [comment]
Same problem here

**Comment by exislow** [comment]
Duplicate #22 (https://github.com/exislow/tidal-dl-ng/issues/22#issuecomment-1923492562)

**Comment by NoDowt** [comment]
> Duplicate #22 ([#22 (comment)](https://github.com/exislow/tidal-dl-ng/issues/22#issuecomment-1923492562))

Yep i understand the relation between extensions/containers & difference to codec; just thought it was odd that the same track was previously downloaded as FLAC extension/container but re-downloading now had m4a.

Obviously Tidal handling it differently from their end now... maybe around the MQA/HiRes Lossless changes they did a while back.
