### ISSUE TITLE
[Feature] Include Explicit tag in search result & file/track name

### ISSUE THREAD

**Issue by NoDowt** [exislow/tidal-dl-ng#82]
### Current Situation

Tidal natively shows when tracks are flagged as explicit, and the original Tidal-DL included the (Explicit) flag in the track title naming.
Currently, Tidal-dl-ng doesn't flag explicit files at all. This makes it hard to get the correct version you're after when there is a clean & explicit version.

### Suggestion / Feature Request

Have any files flagged as explicit shows in the search results as such for easy identification.
Also include (Explicit) in the track title so both clean & explicit versions of the same song can be collected easily.

**Comment by exislow** [comment]
Thank you for this suggestion. I will have a look into this.

**Comment by exislow** [comment]
From the next release on you can use the explicit tag like this in your config:

```json
"format_album":
        "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}"

"format_track": "Tracks/{artist_name} - {track_title}{track_explicit}"
"format_video": "Videos/{artist_name} - {track_title}{track_explicit}"
```

If the track / album is an explicit version, the tag will be replaced with " (Explicit)" otherwise it will be removed.
