### ISSUE TITLE
Only downloads upto 48000khz (which i think is mqa). HiRes Lossless (TIDAL MAX) not working.

### ISSUE THREAD

**Issue by duckyz1** [exislow/tidal-dl-ng#9]
Hello,

While trying to download 24bit/192khz songs from Tidal it seems like Tidal-dl new gen can only download up to 48khz I think it is MQA (same with Yaronzz's tidal-dl) 

Here you can see the track is 24/192 
![image](https://github.com/exislow/tidal-dl-ng/assets/80813542/a556d0e5-8bf3-4047-908b-e42ed6397b3d)

after I've downloaded it using your GUI
![image](https://github.com/exislow/tidal-dl-ng/assets/80813542/f202476f-e7b2-426c-8ddf-b99424ef83d1)

I put it into foobar2000
![image](https://github.com/exislow/tidal-dl-ng/assets/80813542/1b4350fd-180f-45ed-8241-fb5a9560cbf1)

and it shows up as being 48000hz 

It would be cool if you could fix up Tidal-dl new gen and support the downloading of Tidal hi-res lossless and not being directed to mqa instead. 

If this is a user issue please let me know how to fix it, it'll be greatly appreciated.

**Comment by exislow** [comment]
Thanks for your report. Do you have the tidal max plan? Can you post the link of the song so I can try to re-produce it?

**Comment by typingbeaver** [comment]
Song is https://tidal.com/browse/track/68646787

This Song is indeed an MQA song, which gets upscaled from 24 bits/48kHz to 24 bits/192kHz - also by Tidal I guess. So there is no "real" lossless 192kHz file available, only 48kHz with MQA.
![file](https://github.com/exislow/tidal-dl-ng/assets/74824542/534a146b-ed39-45d5-a661-7e5b9a9d00fb)
![file_mqa](https://github.com/exislow/tidal-dl-ng/assets/74824542/94741821-1d4b-4210-8705-6dc777fd5712)


I don't think there can be done much, as the download is handled by the `tidalapi` package and not this downloader itself.

**Comment by typingbeaver** [comment]
The only way to get true 24 bits/192kHz FLACs is by grabbing a token from the official application itself. 3rd party applications via browser login (like this one) only get 24 bits/48kHz max.
See [this issue](https://github.com/tamland/python-tidal/issues/188)

**Comment by exislow** [comment]
I think I know why this happens. Only the following devices are allowed to download MAX: https://tidal.com/supported-devices?filter=hires-flac

Thus, I need a `client_id` and the `client_secret` of one of these devices to be able to enable this app to download MAX. This needs some serious reverse engineering. Let me see, what I can do.

**Comment by exislow** [comment]
Does anybody know a TIDAL GitHub project, which is able to download with MAX resolution?

**Comment by exislow** [comment]
I think I have found the solution. But I need a temporary TIDAL MAX account to finish development. It would be really helpful, if anybody likes to donate something / create me a temporary family account with a TIDAL MAX subscription to be able to finish this issue.

**Comment by rgnet1** [comment]
Hi, I'm willing to share my credentials if you need it. I have a personal account but i do not use it that often. Add me on discord. my username is: rumz

**Comment by exislow** [comment]
Thanks a lot! I did, just waiting for you to confirm my friend request.

**Comment by rgnet1** [comment]
Oh I don't think I got it. Put a dot in front: .rumz

I forgot discord does that

**Comment by exislow** [comment]
Closing this issue here, since I am going to tackle this topic here: https://github.com/tamland/python-tidal/issues/188
