### ISSUE TITLE
[Bug] Lyrics not working under certain circumstances

### ISSUE THREAD

**Issue by mrambossek** [exislow/tidal-dl-ng#95]
### What happened?

Hi,

i managed to get the project working in general, but seem to be unable to dump lyrics. or rather, i think it worked once, but no longer...?

maybe it has something to do with https://github.com/exislow/tidal-dl-ng/issues/93#issuecomment-2068204386, but even when i disable extract_flac , i dont get lyrics anymore (at all). ideally, i would like to have them put into the flac, but i guess since [that track](https://listen.tidal.com/album/7780551/track/7780552) is using an m4a container, lyrics_embed does not transfer them..?

in the log, i did see a 404, and when sniffing it with fiddler, it kinda looks to me as if the api endpoint called simply doesnt exist?
`api.tidal.com GET /v1/tracks/[xx]/lyrics?sessionId=[xx]&countryCode=[xx]&limit=10000 HTTP/1.1`
the web player seems to call this instead
`listen.tidal.com GET /v1/tracks/[xx]/lyrics?countryCode=[xx]&locale=[xx]&deviceType=BROWSER HTTP/1.1`

from what i understand this project uses the tidalapi library for those things, i checked issues there but did not find anything either. let me know if i should open the issue there instead please :)

i also checked https://developer.tidal.com/apiref?spec=catalogue but cannot find anything there regarding lyrics. is that the problem, maybe? is there no lyrics support at all via API - but in the player it works?

thanks!

### Version App

v0.13.1

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
HTTP error on 404
Could not retrieve lyrics for `Muse - Space Dementia`.
Next download will start in 4.0 seconds.
```

### Your settings

```json
{
    "skip_existing": "extension_ignore",
    "lyrics_embed": true,
    "lyrics_file": true,
    "video_download": false,
    "download_delay": true,
    "download_base_path": "D:\\_tempdone\\tidal",
    "quality_audio": "HI_RES_LOSSLESS",
    "quality_video": "1080",
    "format_album": "Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}",
    "format_playlist": "Playlists/{playlist_name}/{artist_name} - {track_title}",
    "format_mix": "Mix/{mix_name}/{artist_name} - {track_title}",
    "format_track": "Tracks/{artist_name} - {track_title}{track_explicit}",
    "format_video": "Videos/{artist_name} - {track_title}{track_explicit}",
    "video_convert_mp4": false,
    "path_binary_ffmpeg": "C:\\ProgramData\\chocolatey\\lib\\ffmpeg-full\\tools\\ffmpeg\\bin\\ffmpeg.exe",
    "metadata_cover_dimension": "1280",
    "extract_flac": false,
    "downgrade_on_hi_res": false
}
```

**Comment by exislow** [comment]
Cannot help you, since you have redacted all information necessary for reproduction.

**Comment by mrambossek** [comment]
Sorry i only removed parts i considered irrelevant, the track I tried is fully linked. I can re dump requests in a few hours if that helps. I figured it would be something more generic due to the missing api etc..

**Comment by mrambossek** [comment]
ok, i have no idea whats going on - but simply retrying the same actions, it mostly works now. that is, i no longer see the 404 error.

however, as saving the lyrics into a seperate file when extracting from m4a seems to not work for me, but i will comment in that other issue about it.

since i cannot reproduce the general 404 stuff anymore, i will close this, thanks
