### ISSUE TITLE
[Feature] handle multi-Volume Albums in a nicer way

### ISSUE THREAD

**Issue by mrambossek** [exislow/tidal-dl-ng#97]
### Current Situation

when you download an album with multiple Volumes - for example id 35392099
the current behaviour is that you end up with 2 files starting with "01. " because (i assume) it just uses the "track id" to generate the filename:

```
01. Mumford & Sons - Sigh No More.flac
01. Mumford & Sons - Sigh No More (Live At Shepherd's Bush Empire).flac
```

### Suggestion / Feature Request

i am not sure if this is even possible via their api / tidalapi, but if it is, it would be nice to detect multi-volume albums and, for example, name files like "{volume}{trackid}. ", ie:
```
101. Mumford & Sons - Sigh No More.flac
201. Mumford & Sons - Sigh No More (Live At Shepherd's Bush Empire).flac
```

this probably requires introducing an additional variable into the naming template, from the default
`Albums/{album_artist} - {album_title}{album_explicit}/{album_track_num}. {artist_name} - {track_title}`
to
`Albums/{album_artist} - {album_title}{album_explicit}/{album_vol_num}{album_track_num}. {artist_name} - {track_title}`
.. or something like that

looking at https://tidalapi.netlify.app/api#module-tidalapi.album, i do see a num_volumes here, which could potentially be used to decide on the number of digits (zero-padding), but i didn't find info on a single "track".

thanks :)

**Comment by exislow** [comment]
Have you already had a look at this? https://github.com/exislow/tidal-dl-ng/issues/90

**Comment by exislow** [comment]
Closed due to stale.
